/* AI NOBORu — https://www.aiofonesown.com/
 * Curated English copy for values returned by the shared calculation engines.
 * Japanese source strings remain as lookup keys; mathematics is never rewritten here.
 */
export const engineCopy=[
['左の円の半径を入力してください。','Enter the radius of the circle on the left.'],
['辺を倍にする回数を入力してください。','Enter the number of times the side count is to be doubled.'],
['値は2〜12個、カンマ区切りで入力してください。','Enter 2–12 comma-separated values.'],
['0以上の小数を160文字以内で入力してください（指数表記は使えません）。','Enter a non-negative decimal of no more than 160 characters; scientific notation is not accepted.'],
['係数を2〜9個、最高次から入力してください（1〜8次）。','Enter 2–9 coefficients in descending order of degree (degree 1–8).'],
['条件は1〜10行で入力してください。','Enter between 1 and 10 conditions, one per line.'],
['項数 nは80桁以内の整数で入力してください。','Enter the number of terms n as an integer of no more than 80 digits.'],
['鶴 6羽\n亀 4匹','6 cranes\n4 turtles'],
['頭 10、足 28','10 heads, 28 legs'],
['種類','Animal'],
['数','Number'],
['足の合計','Total legs'],
['鶴','Cranes'],
['亀','Turtles'],
['全部を鶴と考えると、足は 10 × 2 = 20 本。','If all 10 animals were cranes, they would have 10 × 2 = 20 legs.'],
['実際との差は 28 − 20 = 8 本。','The difference from the actual total is 28 − 20 = 8 legs.'],
['鶴を亀に替えると2本増えるので、亀は 8 ÷ 2 = 4 匹。','Replacing a crane with a turtle adds two legs, so there are 8 ÷ 2 = 4 turtles.'],
['検算：6 + 4 = 10、2 × 6 + 4 × 4 = 28。','Check: 6 + 4 = 10, and 2 × 6 + 4 × 4 = 28.'],
['整数を厳密計算','Exact integer calculation'],
['頭の数は80桁以内の0以上の整数で入力してください。','Enter the number of heads as a non-negative integer of no more than 80 digits.'],
['6人','6 people'],
['品物の合計 23個','23 items in all'],
['配り方','Distribution'],
['配る総数','Number distributed'],
['品物の合計','Total number of items'],
['3個ずつ','3 each'],
['5個ずつ','5 each'],
['余りと不足を合わせる：5 + 7 = 12。','Combine the surplus and the shortfall: 5 + 7 = 12.'],
['1人分の差：5 − 3 = 2。','Difference per person: 5 − 3 = 2.'],
['人数：12 ÷ 2 = 6。','Number of people: 12 ÷ 2 = 6.'],
['品物：3 × 6 + 5 = 23。','Number of items: 3 × 6 + 5 = 23.'],
['少ない配り方は80桁以内の0以上の整数で入力してください。','Enter the smaller number given to each person as a non-negative integer of no more than 80 digits.'],
['2 から、7倍を 12回','Start at 2 and multiply by 7 for 12 steps.'],
['その時点の数','Value at that stage'],
['0（はじめ）','0 (start)'],
['0回目は 2。','At step 0, the value is 2.'],
['次の数 = 今の数 × 7。','Next value = current value × 7.'],
['最後の数 = 2 × 7^12 = 27682574402。','Final value = 2 × 7^12 = 27682574402.'],
['最初の数は80桁以内の0以上の整数で入力してください。','Enter the starting value as a non-negative integer of no more than 80 digits.'],
['8回','8 pours'],
['いずれかの容器に 5 を量る最短の注ぎ回数','Fewest pours needed to measure 5 in any one container'],
['注ぎ方','Pour'],
['はじめ','Start'],
['初めは A に 10、B と C は空。','Begin with 10 in A; B and C are empty.'],
['注ぐ元が空になるか、注ぐ先が満杯になるまで注ぎます。途中では止めません。','Pour until the source is empty or the destination is full; do not stop midway.'],
['各状態で可能な注ぎ方を、回数の少ない順に探索しました。','The search considers every possible pour in order of increasing move count.'],
['最後の量：2、5、3。合計は常に 10。','Final amounts: 2, 5, 3. Their total remains 10 throughout.'],
['最短手順を整数で探索','Shortest-path search over integer states'],
['容器Aは3桁以内の0以上の整数で入力してください。','Enter the capacity of container A as a non-negative integer of no more than 3 digits.'],
['斜辺の長さ（入力と同じ単位）','Length of the hypotenuse (in the input unit)'],
['辺','Side'],
['長さ','Length'],
['勾 a','Leg kō, a'],
['股 b','Leg ko, b'],
['弦 c（近似）','Hypotenuse c (approx.)'],
['平方の和は厳密・平方根は近似','Exact sum of squares; approximate square root'],
['勾 aは30文字以内の正の小数で入力してください。','Enter leg a as a positive decimal of no more than 30 characters.'],
['三角形の面積（入力単位の2乗）','Area of the triangle (square input units)'],
['量','Quantity'],
['値','Value'],
['半周 s','Semiperimeter s'],
['面積の平方（厳密）','Area squared (exact)'],
['面積（近似）','Area (approx.)'],
['半周 s = (a + b + c) ÷ 2 = 21。','Semiperimeter s = (a + b + c) ÷ 2 = 21.'],
['面積の平方 = s(s−a)(s−b)(s−c) = 7056。','Area squared = s(s−a)(s−b)(s−c) = 7056.'],
['面積 = √(7056) ≈ 84。','Area = √(7056) ≈ 84.'],
['面積の平方は厳密・平方根は近似','Exact area squared; approximate square root'],
['辺 aは30文字以内の正の小数で入力してください。','Enter side a as a positive decimal of no more than 30 characters.'],
['1.25992104989487316476 ≤ ∛N < 1.25992104989487316477（指定桁で切り捨て）','1.25992104989487316476 ≤ ∛N < 1.25992104989487316477 (truncated to the requested precision)'],
['下ろす3桁','Next three-digit group'],
['選ぶ桁','Digit chosen'],
['ここまでの桁列','Digits found so far'],
['数を3桁ずつ区切り、余りに次の3桁を下ろします。','Group the number into blocks of three digits, then bring the next block down beside the remainder.'],
['既決の桁列を r、次の桁を q として、(300r² + 30rq + q²)q が下ろした数を超えない最大の q を選びます。','Let r be the digits already found and q the next digit. Choose the largest q for which (300r² + 30rq + q²)q does not exceed the current dividend.'],
['立方したときに入力値を超えない条件で、次の一桁を確定します。','Each new digit is chosen so that the resulting cube does not exceed the input value.'],
['整数計算による厳密な上下区間','Exact bounds obtained with integer arithmetic'],
['0以上の整数・小数を100文字以内で入力してください。指数表記は使えません。','Enter a non-negative integer or decimal of no more than 100 characters. Scientific notation is not accepted.'],
['y を消去した 2次式。実数の候補は元の2式への代入が必要です。','A quadratic obtained by eliminating y. Candidate real roots must be checked in the two original equations.'],
['係数・式','Coefficient or expression'],
['f の y係数 A(x)','Coefficient A(x) of y in f'],
['f の定数 B(x)','Constant term B(x) in f'],
['g の y係数 C(x)','Coefficient C(x) of y in g'],
['g の定数 D(x)','Constant term D(x) in g'],
['終結式 R(x)','Resultant R(x)'],
['解を変えない整数係数','Integer coefficients preserving the solution set'],
['シルベスター行列： [1,A,B,0] / [0,1,A,B] / [1,C,D,0] / [0,1,C,D]。','Sylvester matrix: [1,A,B,0] / [0,1,A,B] / [1,C,D,0] / [0,1,C,D].'],
['この4×4行列式を展開すると R=(B−D)²+(A−C)(AD−BC)。','Expanding this 4×4 determinant gives R=(B−D)²+(A−C)(AD−BC).'],
['A(x)≠C(x)なら y=−(B−D)/(A−C) を元の式へ代入。A=C なら B=D も必要で、y²+Ay+B の判別式が0以上か確認します。','If A(x)≠C(x), substitute y=−(B−D)/(A−C) into the original equations. If A=C, B=D is also required, and the discriminant of y²+Ay+B must be non-negative.'],
['R=0 は複素数の共通根の条件です。実数の y や、幾何の長さが正であることまで保証しません。','R=0 is the condition for a common complex root. It does not by itself guarantee a real y or a positive geometric length.'],
['多項式を整数で厳密展開','Exact polynomial expansion over the integers'],
['係数は最高次から、3個以内の整数で入力してください。','Enter no more than 3 integer coefficients, in descending order of degree.'],
['2個の異なる実根','2 distinct real roots'],
['次数 4 ／ 重複を数えた実根 4個','Degree 4 / 4 real roots counted with multiplicity'],
['根','Root'],
['小数の目安','Decimal approximation'],
['厳密区間 (左, 右] または厳密値','Exact interval (left, right] or exact value'],
['重複度','Multiplicity'],
['式：x^4 − 2x^3 − 3x^2 + 4x + 4 = 0。','Equation: x^4 − 2x^3 − 3x^2 + 4x + 4 = 0.'],
['全実根は (−4, 4) にあります。','All real roots lie in (−4, 4).'],
['f と f′ の最大公約因子を取り、重根を除いた式のSturm列を作ります。','Take gcd(f,f′), remove repeated factors, and form the Sturm sequence of the square-free polynomial.'],
['零を除いた符号変化数 V(a)−V(b) で、半開区間 (a,b] の異なる実根を数えます。','The difference V(a)−V(b) in sign variations, with zeros omitted, counts the distinct real roots in the half-open interval (a,b].'],
['4回の区間分割で、各区間を1根ずつに分離しました。','Four interval subdivisions isolate one root in each interval.'],
['重複度は最大公約因子の連鎖で厳密に検査しています。小数欄は区間中点からの目安で、厳密値ではありません。','Multiplicities are checked exactly through a chain of gcds. The decimal column uses interval midpoints as guides, not exact values.'],
['現代的補助：Sturm列・有理数区間','Modern aid: Sturm sequences and rational intervals'],
['係数は最高次から、9個以内の整数で入力してください。','Enter no more than 9 integer coefficients, in descending order of degree.'],
['40項の級数から得た円弧長の厳密な包含区間','Certified enclosure for the arc length from a 40-term series'],
['項 n','Term n'],
['加える分数','Fraction added'],
['部分和','Partial sum'],
['z=c/d=1/4。弧長の平方を s²=4d² Σ tₙ と表します。','Set z=c/d=1/4 and write the squared arc length as s²=4d² Σ tₙ.'],
['残りの項の和は 1/1071094320610228326087120060 より小さい（正項かつ項比<z）。','The sum of the remaining terms is less than 1/1071094320610228326087120060 (all terms are positive and the term ratio is <z).'],
['弧長平方の上下界から、整数平方根で外向きに小数32桁へ丸めました。','Starting from bounds on the squared arc length, integer square roots are used to round outward to 32 decimal places.'],
['円弧長の平方の級数を、現代の逆三角関数と同値な形で計算しています。','The series for the squared arc length is evaluated in a form equivalent to a modern inverse trigonometric expression.'],
['正項級数と剰余上限による厳密区間','Certified interval from a positive-term series and a remainder bound'],
['整数・小数・分数（例 3/4）で入力してください。','Enter an integer, decimal, or fraction (for example, 3/4).'],
['小数50桁を切り捨てで確定 ／ 80項','50 decimal places certified by truncation / 80 terms'],
['項数','Number of terms'],
['下界 L < π','Lower bound L < π'],
['上界 π < U','Upper bound π < U'],
['円弧平方の級数に z=1/4 を入れると π²=18Σ1/(n² C(2n,n))。','Substituting z=1/4 into the squared-arc series gives π²=18Σ1/(n² C(2n,n)).'],
['次項への比は n²/(2(n+1)(2n+1))<1/4。','The ratio of successive terms is n²/(2(n+1)(2n+1))<1/4.'],
['π²の残差は次項の24倍より小さい。','The remainder in π² is less than 24 times the next term.'],
['上下界の平方根を整数計算し、指定桁で切り捨てた値が一致した時だけ確定します。','The square roots of the two bounds are computed with integer arithmetic; digits are certified only when their truncated values agree at the requested precision.'],
['表は安全側へ丸めた L < π < U。最終行の U は表示値の最後の桁を1増やした数で、その値未満であることを保証します。','The table gives outward-rounded bounds L < π < U. In the final row, U is the displayed value with its last digit increased by one, certifying that π is smaller than that number.'],
['建部と同値な円弧級数から導く現代的な計算であり、史料に残る円周率計算の全手順の再現ではありません。','This is a modern calculation derived from an arc series equivalent to Takebe’s; it is not a reconstruction of every step in the historical computation of π.'],
['上下界が一致した桁を確定','Digits certified where the two bounds agree'],
['小数点以下の桁数は1〜50の整数にしてください。','Enter an integer from 1 to 50 for the number of decimal places.'],
['半径 0.1547005383793','Radius 0.1547005383793'],
['表示：解1。2つの解は別々の配置です。','Showing solution 1. The two solutions are separate configurations.'],
['解','Solution'],
['符号付き曲率','Signed curvature'],
['半径 / 境界','Radius / boundary'],
['中心 / 境界式','Center / boundary equation'],
['接触誤差','Tangency residual'],
['2.154700538379（包囲）','2.154700538379 (enclosing circle)'],
['3つの円の中心間距離を、半径の和として三角形を作ります。','Form the triangle of centers, taking each side as the sum of the corresponding radii.'],
['k=1/r とすると、k₄=k₁+k₂+k₃ ± 2√(k₁k₂+k₂k₃+k₃k₁)。','With k=1/r, k₄=k₁+k₂+k₃ ± 2√(k₁k₂+k₂k₃+k₃k₁).'],
['接触条件の平方を引き合わせ、中心座標を求めます。','Subtract the squared tangency equations to obtain the center coordinates.'],
['曲率0は直線。負の曲率は包囲円で、その実際の半径は |1/k|。','Zero curvature represents a line. Negative curvature represents an enclosing circle, whose radius is |1/k|.'],
['3つの与円それぞれと、選んだ解の距離を検算しています。','Distances from the selected solution to each of the three given circles are checked.'],
['中心間距離による検算付き・小数近似','Decimal approximation with center-distance checks'],
['解1','Solution 1'],
['解2','Solution 2'],
['半径 0.2247448713916','Radius 0.2247448713916'],
['2.224744871392（包囲）','2.224744871392 (enclosing sphere)'],
['最初の4球は6組すべての中心間距離を検査します。','For the first four spheres, all six center-to-center distances are checked.'],
['S=Σkᵢ、Q=Σkᵢ² とし、S²−2Q が負なら与えた4球を配置できません。','Let S=Σkᵢ and Q=Σkᵢ². If S²−2Q is negative, the four given spheres cannot be arranged as specified.'],
['5球では (Σkᵢ)²=3Σkᵢ²。第5球の曲率は (S ± √(3S²−6Q))/2。','For five mutually tangent spheres, (Σkᵢ)²=3Σkᵢ². The fifth curvature is (S ± √(3S²−6Q))/2.'],
['中心座標も求め、各候補を4つの球との距離で検算します。','The center is also calculated, and each candidate is checked by its distances from the four spheres.'],
['曲率0は平面。最初の4球の中心が同一平面の場合は、同じ半径で面の両側にある2解を別々に扱います。','Zero curvature represents a plane. When the first four centers are coplanar, the two equal-radius solutions on opposite sides of that plane are treated separately.'],
['6球で、同じ位置へ','Six spheres return to the starting position'],
['接触24組・非隣接9組を検算 ／ 閉鎖誤差/R 2.775557561563e-16','Checked 24 tangencies and 9 non-adjacent pairs / closure residual divided by R: 2.775557561563e-16'],
['球','Sphere'],
['半径','Radius'],
['直径','Diameter'],
['中心 (x, y, z)','Center (x, y, z)'],
['甲','A'],['乙','B'],['丙','C'],['丁','D'],['戊','E'],['己','F'],
['甲へ戻る','Return to A'],
['外球と日球の接点を中心に反転すると、2つの境界は平行な平面になります。','Invert about the point where the outer sphere touches the Sun sphere; the two boundaries become parallel planes.'],
['その間では、月球と連鎖する球は同じ半径。中心は正六角形の周りを60度ずつ進みます。','Between those planes, the Moon sphere and the chain spheres have the same radius, and their centers advance by 60° around a regular hexagon.'],
['6球を元の空間へ反転し直し、中心座標と半径を計算します。','Invert the six spheres back into the original space and calculate their centers and radii.'],
['最大接触誤差/R：3.885780586188e-16。非隣接球の最小の隙間/R：0.1549356561837。','Maximum tangency residual / R: 3.885780586188e-16. Minimum gap between non-adjacent spheres / R: 0.1549356561837.'],
['直径の一致だけでなく、7番目の中心と半径が最初の球へ戻ることを検査しています。','The check verifies not just equality of diameters, but also that the seventh center and radius return to those of the first sphere.'],
['図は3次元の正投影です。見かけの重なりは球の衝突を意味しません。見る向きを変えて確かめられます。','The diagram is an orthographic projection in three dimensions. Apparent overlap does not mean the spheres intersect; rotate the view to inspect the configuration.'],
['反転幾何による構成・小数で接触検算','Construction using inversion geometry, with numerical tangency checks'],
['甲へ','to A'],
['甲—外','A—outer'],['甲—日','A—Sun'],['甲—月','A—Moon'],['甲—乙','A—B'],
['乙—外','B—outer'],['乙—日','B—Sun'],['乙—月','B—Moon'],['乙—丙','B—C'],
['丙—外','C—outer'],['丙—日','C—Sun'],['丙—月','C—Moon'],['丙—丁','C—D'],
['丁—外','D—outer'],['丁—日','D—Sun'],['丁—月','D—Moon'],['丁—戊','D—E'],
['戊—外','E—outer'],['戊—日','E—Sun'],['戊—月','E—Moon'],['戊—己','E—F'],
['己—外','F—outer'],['己—日','F—Sun'],['己—月','F—Moon'],['己—甲','F—A'],
['甲—丙','A—C'],['甲—丁','A—D'],['甲—戊','A—E'],['乙—丁','B—D'],['乙—戊','B—E'],['乙—己','B—F'],['丙—戊','C—E'],['丙—己','C—F'],['丁—己','D—F'],
['日','Sun'],['月','Moon'],
['1^10 から 10^10 までの厳密な和','Exact sum from 1^10 through 10^10'],
['ベルヌーイ係数 βⱼ','Bernoulli coefficient βⱼ'],
['N の次数','Power of N'],
['和の多項式の係数','Coefficient in the sum polynomial'],
['ここでは β₁=+1/2 の約束を使います。β₁=−1/2 の表とは一次項の符号の約束が異なります。','Here β₁=+1/2 is used. Tables using β₁=−1/2 follow the other common convention for the first Bernoulli number.'],
['βⱼ を有理数の三角漸化式で生成し、S(N)=Σ C(p+1,j)βⱼN^(p+1−j)/(p+1) に入れます。','Generate βⱼ by a triangular recurrence over the rationals, then substitute it into S(N)=Σ C(p+1,j)βⱼN^(p+1−j)/(p+1).'],
['全係数について S(N)−S(N−1)=N^p、S(0)=0 を厳密に検算しています。','The identities S(N)−S(N−1)=N^p and S(0)=0 are checked exactly coefficient by coefficient.'],
['p=0 は N 個の1の和です。N=0 の空の和は0です。','For p=0, the expression sums N copies of 1. When N=0, the empty sum is 0.'],
['有理数係数・整数の和・差分恒等式を厳密計算','Exact rational coefficients, integer sum, and finite-difference identity'],
['最後の数 N は0以上、80桁以内の整数にしてください。','Enter the final value N as a non-negative integer of no more than 80 digits.'],
['また I(p,q)=I(p+1,q)+I(p,q+1)。x+(1−x)=1 を積分した関係です。','Also, I(p,q)=I(p+1,q)+I(p,q+1), obtained by integrating the identity x+(1−x)=1.'],
['区間は0から1。被積分関数は x^p(1−x)^q。','The interval is 0 to 1, and the integrand is x^p(1−x)^q.'],
['表は p≤2、q≤3 の部分。指定した指数の答えは上の結果です。','The table shows the portion with p≤2 and q≤3; the result for the requested exponents appears above.'],
['分数、または分数×π の厳密値','Exact value as a fraction or a fraction times π'],
['積分の種類は1〜2の整数にしてください。','Choose the integral type by entering 1 or 2.'],
['100項 ／ 楕円の周長の保証された区間','100 terms / certified interval for the perimeter of the ellipse'],
['加える項の下界','Lower bound for the term added'],
['加える項の上界','Upper bound for the term added'],
['大きい半径・半長軸 a=5、小さい半径・半短軸 b=3。m=16/25。','Major radius or semimajor axis a=5; minor radius or semiminor axis b=3. m=16/25.'],
['正の残差は (N+2)t_(N+1) 以下。m<1 では t_(N+1)/(1−m) と比べ小さい上限を使います。N=100。','The positive remainder is at most (N+2)t_(N+1). When m<1, the smaller of this bound and t_(N+1)/(1−m) is used. N=100.'],
['各段を小数50桁で外向きに丸め、残差上限と確定したπの区間を掛け、結果を小数24桁で外向きに丸めました。','At each stage, values are rounded outward to 50 decimal places. The remainder bound is combined with a certified interval for π, and the final result is rounded outward to 24 decimal places.'],
['区間の幅：19/500000000000000000000000。表示24桁すべてが確定桁という意味ではありません。','Interval width: 19/500000000000000000000000. This does not mean that all 24 displayed decimal places are certified digits.'],
['剰余と丸め誤差を含む包含区間','Enclosing interval including remainder and rounding error'],
['100項 ／ 直角に交わる円柱の共通体積の保証された区間','100 terms / certified interval for the common volume of two perpendicular cylinders'],
['大きい半径・半長軸 a=2、小さい半径・半短軸 b=1。m=1/4。','Major radius or semimajor axis a=2; minor radius or semiminor axis b=1. m=1/4.'],
['区間の幅：1/1000000000000000000000000。表示24桁すべてが確定桁という意味ではありません。','Interval width: 1/1000000000000000000000000. This does not mean that all 24 displayed decimal places are certified digits.'],
['2次の必要条件。最高次係数が消える x と、実数の y の存在は元の式で確認します。','A quadratic necessary condition. Values of x that make a leading coefficient vanish, and the existence of a real y, must be checked in the original equations.'],
['換式','Eliminant'],
['入力順に前式 f、後式 g とします。','The equations are designated f and g in the order entered.'],
['前式の y 次数 n=3、後式 m=2。係数 aⱼ,bⱼ は x の多項式です。','The degree in y is n=3 for f and m=2 for g. The coefficients aⱼ and bⱼ are polynomials in x.'],
['m<i≤n では hᵢ=y^(i−m−1)g。すべて y の n 次未満になります。','For m<i≤n, hᵢ=y^(i−m−1)g. Every resulting expression has degree less than n in y.'],
['3×3 の換式行列の行列式：x^2 − 1。','Determinant of the 3×3 elimination matrix: x^2 − 1.'],
['5×5 のシルベスター行列式とも、符号 (−1)^(nm) を含め厳密に一致しました。','It agrees exactly with the 5×5 Sylvester determinant, including the sign factor (−1)^(nm).'],
['最高次係数 aₙ(x)=1、bₘ(x)=1。これらが消える候補では、次数が落ちて見かけの解が出ることがあります。','The leading coefficients are aₙ(x)=1 and bₘ(x)=1. At candidate values where either vanishes, a drop in degree can produce an extraneous solution.'],
['例：xy+1=0、xy+2=0 は消去式が x=0 でも、代入すると1=0、2=0で解がありません。','Example: for xy+1=0 and xy+2=0, the eliminant gives x=0, but substitution gives 1=0 and 2=0, so there is no solution.'],
['零式は有理関数係数で共通因子があることを示します。すべての実数 x に実数解 y があるという意味ではありません。','An identically zero eliminant indicates a common factor over rational functions. It does not mean that a real y exists for every real x.'],
['下のボタンから、この係数を実根の計算へ渡せます。','Use the button below to send these coefficients to the real-root calculator.'],
['二つの行列式を整数多項式で厳密照合','Exact comparison of two determinants as integer polynomials'],
['y の最高次から定数項まで、2〜5行で入力してください。','Enter 2–5 rows, from the highest power of y down to the constant term.'],
['中心 (3/2, 0)\n半径 1/2','Center (3/2, 0)\nRadius 1/2'],
['反転後の円を、中心と半径まで厳密に計算。','Exact center and radius of the inverted circle.'],
['元の円の中心','Original circle center'],
['元の円の半径','Original circle radius'],
['中心点そのものの反転','Image of the center point itself'],
['反転後の円の中心','Inverted circle center'],
['反転後の半径','Inverted radius'],
['反転の中心は原点、半径 k=2。点 P の像は k²P/|P|²。','The center of inversion is the origin and the inversion radius is k=2. The image of a point P is k²P/|P|².'],
['Δ≠0 なら円の中心は k²(x,y)/Δ、半径は |k²r/Δ|。','If Δ≠0, the inverted circle has center k²(x,y)/Δ and radius |k²r/Δ|.'],
['Δ=0 の円は直線へ。式は x₀x+y₀y=k²/2。ゼロで割らず、分数の一致で判定しています。','A circle with Δ=0 maps to the line x₀x+y₀y=k²/2. The case is detected by exact equality of fractions, without division by zero.'],
['元の円の中心点の像と、反転後の円の中心は一般には異なります。','In general, the image of the original center point is not the center of the inverted circle.'],
['反転を2回行うと、元の中心と半径へ戻ることを厳密に確認しました。','A second inversion is checked to return exactly to the original center and radius.'],
['原点そのものに像はありません。原点で接する円どうしは平行な直線になる場合があり、その接触点は有限の場所へは移りません。','The origin itself has no image. Circles tangent at the origin may map to parallel lines, and their point of tangency does not map to a finite point.'],
['分数による厳密値・図は小数表示','Exact fractional values; decimal diagram'],
['6円で閉鎖（条件は厳密）','Closes after 6 circles (exact condition)'],
['開始角を変え、個々の半径が変わっても同じ輪になるか試せます。','Change the starting angle to see whether the same ring closes even as the individual radii change.'],
['円','Circle'],
['中心 x','Center x'],
['中心 y','Center y'],
['戻り位置 7','Return position 7'],
['閉鎖を決める量 C=(R²+r²−d²)/(2Rr)=5/3。','The closure parameter is C=(R²+r²−d²)/(2Rr)=5/3.'],
['同心円へ移したときの1歩 δ=60度。1周に必要な個数 2π/δ≈6。','After transforming the two boundary circles into concentric circles, the angular step is δ=60 degrees, so 360°/δ≈6 circles are needed for one revolution.'],
['nδ−360°=1.017777498068e-13度。必要な個数を丸めて閉鎖と判定することはありません。','nδ−360°=1.017777498068e-13 degrees. Closure is not decided by rounding the required number of circles.'],
['n=6 では C=5/3 が厳密な閉鎖条件。今回の分数による判定：一致。','For n=6, C=5/3 is the exact closure condition. Exact fractional test for this input: satisfied.'],
['生成した各円の内外接と次の円との接触：最大誤差/R=5.181040781584e-16。','Tangency of every generated circle to both boundaries and to the next circle: maximum residual / R=5.181040781584e-16.'],
['最後と最初の接触誤差/R=1.554312234475e-15。独立に生成した7番目と最初の中心・半径の差/R=2.041903306094e-15。','Tangency residual between the last and first circles / R=1.554312234475e-15. Difference between the independently generated seventh circle and the first in center and radius / R=2.041903306094e-15.'],
['非隣接9組と最初・最後の円の重なり：検出なし。最小すき間/R=-1.554312234475e-15。','Overlap among 9 non-adjacent pairs and the first and last circles: none detected. Minimum gap / R=-1.554312234475e-15.'],
['円の数を増やして何周も進めば戻る配置と、重ならず1周で閉じる輪は別です。ここでは後者を判定します。','A configuration that returns after several revolutions is not the same as a non-overlapping ring that closes in one revolution. This calculator tests the latter.'],
['開始角は同心円へ移した図上の角度。開始位置を動かしても、閉鎖を決める C は変わりません。','The starting angle is measured in the concentric-circle image. Moving the starting position does not change the closure parameter C.'],
['閉鎖条件は分数で証明・配置は数値検算','Exact fractional proof of closure; numerical check of the configuration'],
['正7角形の一辺 ／ 外接円の半径 2','Side length of a regular heptagon / circumradius 2'],
['小数の近似値','Decimal approximation'],
['一辺','Side length'],
['周長','Perimeter'],
['面積','Area'],
['内接円の半径','Inradius'],
['t=2cos(2π/7) と置きます。','Set t=2cos(2π/7).'],
['C₀=2、C₁=t、Cₖ=tCₖ₋₁−Cₖ₋₂。Cₙ(t)−2=0 を整数係数で生成。','Use C₀=2, C₁=t, and Cₖ=tCₖ₋₁−Cₖ₋₂ to generate Cₙ(t)−2=0 with integer coefficients.'],
['この式には、他の回転角に対応する根もあります。求める角は2π/nです。','This polynomial also has roots corresponding to other rotation angles. The angle required here is 2π/n.'],
['辺や面積の数値は三角関数による小数近似。角の多項式の係数は厳密値です。','Lengths and areas are decimal approximations from trigonometric functions; the coefficients of the polynomial in t=2cos(2π/n) are exact.'],
['角の多項式は厳密、長さ・面積は近似','Exact polynomial in t; approximate lengths and area'],
['辺の数は3〜60の整数にしてください。','Enter an integer from 3 to 60 for the number of sides.'],
['係数行列の階数 3 ／ 未知数 3個','Coefficient-matrix rank 3 / 3 unknowns'],
['右辺','Right-hand side'],
['x1 の係数を1にし、他の行から消去。','Scale the pivot coefficient of x1 to 1, then eliminate x1 from the other rows.'],
['x2 の係数を1にし、他の行から消去。','Scale the pivot coefficient of x2 to 1, then eliminate x2 from the other rows.'],
['x3 の係数を1にし、他の行から消去。','Scale the pivot coefficient of x3 to 1, then eliminate x3 from the other rows.'],
['特解：(1, 2, 3)。','Particular solution: (1, 2, 3).'],
['特解を元の式へ代入し、自由変数の各方向で右辺が0になることも厳密照合。','Substitution verifies the particular solution in the original equations and confirms exactly that every free-variable direction gives a zero right-hand side.'],
['分数による消去と再代入','Elimination and back-substitution over exact fractions'],
['連立方程式は1400文字以内で入力してください。','Enter a linear system of no more than 1,400 characters.'],
['共通因子の次数 1。最高次係数を1にそろえています。','The common factor has degree 1 and has been normalized to leading coefficient 1.'],
['前の式（整数化）','Previous polynomial (cleared to integers)'],
['次の式（整数化）','Next polynomial (cleared to integers)'],
['定数倍を除いた余式','Remainder up to a nonzero constant factor'],
['分母を払って整数化し、擬除法と係数の共通因子の除去で次数を下げます。大きな余式は表では概要を表示します。','Clear denominators, then reduce the degree by pseudo-division and removal of the common content of the coefficients. Long remainders are abbreviated in the table.'],
['両方の式を共通因子で割り、余りが0であることを厳密に検算。','Divide both polynomials by the common factor and verify exactly that both remainders are zero.'],
['共通因子が1なら、複素数まで含めて共通根はありません。','If the gcd is 1, the polynomials have no common root, even over the complex numbers.'],
['有理数係数の最大公約因子','Greatest common divisor over the rationals'],
['係数は全体で1400文字以内にしてください。','Keep the complete coefficient input within 1,400 characters.'],
['重根はありません（複素数も含む）。','There are no repeated roots, including complex roots.'],
['次数','Degree'],
['7行のシルベスター行列式から終結式を計算。','Compute the resultant from the determinant of the 7×7 Sylvester matrix.'],
['D=0 と gcd(f,f′) の次数が正であることを別々に確かめます。','Check separately that D=0 and that gcd(f,f′) has positive degree.'],
['判別式の符号だけでは、一般の高次方程式の実根数は決まりません。','For a general higher-degree polynomial, the sign of the discriminant alone does not determine the number of real roots.'],
['判別式と共通因子を厳密計算','Exact discriminant and common-factor calculation'],
['重複を含む3個の根の8乗和','Sum of the eighth powers of the 3 roots, counted with multiplicity'],
['累乗 k','Power k'],
['根の累乗和 Sₖ','Power sum of the roots Sₖ'],
['最高次係数で割って xⁿ+a₁xⁿ⁻¹+…+aₙ にそろえます。','Divide by the leading coefficient to put the polynomial in the form xⁿ+a₁xⁿ⁻¹+…+aₙ.'],
['根を個別に求めず、複素根と重複も含めて計算します。S₀=n。','The roots are not solved individually; complex roots and multiplicities are included. S₀=n.'],
['係数から有理数で厳密計算','Exact rational calculation from the coefficients'],
['1.10408951367381233764\n≤ 7乗根 <\n1.10408951367381233765','1.10408951367381233764\n≤ 7th root <\n1.10408951367381233765'],
['隣り合う小数で囲んだ厳密区間。','Exact interval bounded by adjacent decimals.'],
['下端','Lower endpoint'],
['上端','Upper endpoint'],
['対象：2 の実数の7乗根。','Target: the real seventh root of 2.'],
['整数の累乗比較で、小数点を除いた整数を二分探索します。','A binary search compares integer powers after removing the decimal point.'],
['下端を k 乗した値と元の分数を、整数の交差積で比較。','Compare the kth power of the lower endpoint with the original fraction by integer cross-multiplication.'],
['負の奇数乗根は符号を反転すると上下が入れ替わることも反映しています。','For a negative odd root, the reversal of the bounds when the sign is changed is taken into account.'],
['整数比較による厳密区間','Exact interval from integer comparisons'],
['x = u + (1/2) と置いた式','Polynomial after setting x = u + (1/2)'],
['u の次数','Power of u'],
['係数','Coefficient'],
['元の式：x^4 + 2·x^3 − 3·x + 5。','Original polynomial: x^4 + 2·x^3 − 3·x + 5.'],
['最高次の係数から順に (u+h) を掛け、次の係数を加えます。','Starting with the leading coefficient, multiply successively by (u+h) and add the next coefficient.'],
['u=x−h を代入し直し、元の多項式とすべての係数が一致することを検算。','Substitute u=x−h back and verify that every coefficient agrees with the original polynomial.'],
['係数0の項も表に残します。次数や定数項の位置を確かめられます。','Zero-coefficient terms remain in the table so that the powers and the position of the constant term are explicit.'],
['係数を厳密に転位','Exact translation of polynomial coefficients'],
['x^12まで。これより高い次数の項は省略。','Through x^12; higher-degree terms are omitted.'],
['商の係数 cₖ','Quotient coefficient cₖ'],
['分子 A(x)=1。','Numerator A(x)=1.'],
['分母 B(x)=−x^2 − x + 1。','Denominator B(x)=−x^2 − x + 1.'],
['B(x)を掛け戻し、指定次数までA(x)と全係数が一致することを厳密照合。','Multiply back by B(x) and verify exact agreement with every coefficient of A(x) through the requested degree.'],
['形式的な級数です。具体的な x で無限級数が収束するかは、別の条件です。','This is a formal power series. Convergence of the infinite series at a particular value of x is a separate question.'],
['打ち切り次数まで厳密な形式的級数','Formal power series exact through the truncation degree'],
['弦と円弧に挟まれる部分の面積','Area of the circular segment between chord and arc'],
['弦の長さ','Chord length'],
['円弧の長さ','Arc length'],
['円の半径 R=5、弦から円弧までの高さ h=1。','Circle radius R=5; sagitta from the chord to the arc h=1.'],
['h*=min(h,2R−h)、θ=2 asin √(h*/(2R))。小さい側の面積はR²(θ−sinθ cosθ)。','Set h*=min(h,2R−h) and θ=2 asin √(h*/(2R)). The area of the smaller segment is R²(θ−sinθ cosθ).'],
['浅い弧では近い数の引き算を避け、θ−sinθcosθ の級数で計算。','For a shallow arc, use a series for θ−sinθcosθ to avoid subtracting nearly equal numbers.'],
['高さが半径を超えるときは、円全体から反対側の小さな弧の面積を引きます。','When the sagitta exceeds the radius, subtract the smaller segment on the opposite side from the area of the whole circle.'],
['相殺を避けた小数近似','Decimal approximation designed to avoid cancellation'],
['x=a cos t、y=b sin t ／ 0° から 60°','x=a cos t, y=b sin t / 0° to 60°'],
['区間','Interval'],
['長さの下界の近似','Approximate lower bound for length'],
['長さの上界の近似','Approximate upper bound for length'],
['弧長=∫ √(a²sin²t+b²cos²t) dt。角度の入力は度、積分ではラジアン。','Arc length = ∫ √(a²sin²t+b²cos²t) dt. Angles are entered in degrees and converted to radians for integration.'],
['512分割し、それぞれの速度の最小・最大から挟み込みます。','Divide the interval into 512 parts and bound each one using the minimum and maximum speed.'],
['下界 ≈ 3.836485633028、上界 ≈ 3.83972248731。数学上の上下界を小数で近似表示しています。','Lower bound ≈ 3.836485633028; upper bound ≈ 3.83972248731. These are decimal approximations to mathematical bounds.'],
['答えは各区間の両端と中点の速度によるSimpson近似。表示の末尾桁まで保証する区間演算ではありません。','The answer is a Simpson approximation using the speed at both endpoints and the midpoint of each subinterval. It is not interval arithmetic certifying every displayed final digit.'],
['ここでの t は楕円を表す媒介変数の角で、中心から見た点の方角とは異なります。','Here t is the angular parameter of the ellipse, not the polar direction of the point as seen from the center.'],
['区間ごとの速度で挟み込む','Bounds from the speed on each subinterval'],
['区間 [0, 2] を x 軸のまわりに回した体積','Volume obtained by revolving the region between y=P(x) and the x-axis over [0, 2] about the x-axis'],
['P(x)² の係数','Coefficient of P(x)²'],
['積分への寄与（πを除く）','Contribution to the integral (excluding π)'],
['断面は半径 |P(x)| の円。面積は πP(x)²。','Each cross-section is a circle of radius |P(x)| and area πP(x)².'],
['P(x)² を分数係数で展開し、各項を厳密に積分します。','Expand P(x)² with rational coefficients and integrate every term exactly.'],
['P(x)が軸を横切っても、二乗した断面積を積分するので相殺されません。','Even if P(x) crosses the axis, no cancellation occurs because the cross-sectional area πP(x)² is non-negative.'],
['πの係数を厳密計算','Exact calculation of the coefficient of π'],
['10番目の円の半径 ／ 原点は大きい半円の左端','Radius of circle 10 / origin at the left end of the large semicircle'],
['円 n','Circle n'],
['大きい半円の半径 R=a+b=5。左の内円中心は(a,0)、最初の右の内円はn=0。','The large semicircle has radius R=a+b=5. The left inner circle is centered at (a,0), and the first right inner circle is indexed n=0.'],
['外円への内接、左円への外接、直前の円への外接を、中心間距離の二乗で全件厳密照合。','Tangency inside the outer circle, and external tangency to the left circle and the preceding circle, are all verified exactly using squared center distances.'],
['左円と外円の接点へ近づく、一方向の連鎖です。','This one-way chain approaches the point where the left circle touches the outer circle.'],
['全円の座標・半径・接触を分数で検算','Exact fractional checks of every circle’s coordinates, radius, and tangencies'],
['四頂点が一つの円にある凸四角形の面積','Area of a convex cyclic quadrilateral'],
['面積の二乗（厳密）','Area squared (exact)'],
['対角線 AC（近似）','Diagonal AC (approx.)'],
['対角線 BD（近似）','Diagonal BD (approx.)'],
['外接円半径（近似）','Circumradius (approx.)'],
['辺は順に AB=2、BC=3、CD=4、DA=5。','The sides in order are AB=2, BC=3, CD=4, and DA=5.'],
['半周 s=7、面積²=(s−a)(s−b)(s−c)(s−d)=120。','Semiperimeter s=7, and area²=(s−a)(s−b)(s−c)(s−d)=120.'],
['R²=(ac+bd)(ad+bc)(ab+cd)/(16·面積²)。','R²=(ac+bd)(ad+bc)(ab+cd)/(16·area²).'],
['辺だけから一般の四角形の面積は決まりません。四頂点が同じ円上にある条件で計算しています。','The sides alone do not determine the area of a general quadrilateral. This calculation assumes that all four vertices lie on one circle.'],
['平方量は分数で厳密、平方根は近似','Squared quantities are exact fractions; square roots are approximate'],
['六辺の長さから求めた体積（近似）。','Volume from the six edge lengths (approx.).'],
['内積行列','Gram matrix'],
['AB方向','AB direction'],
['AC方向','AC direction'],
['AD方向','AD direction'],
['AからB、C、Dへ向かう三つのベクトルを使います。','Use the three vectors from A to B, C, and D.'],
['内積は u·v=(|u|²+|v|²−|u−v|²)/2。','Compute inner products from u·v=(|u|²+|v|²−|u−v|²)/2.'],
['Gram行列式=1526509670400。体積²=det(G)/36=42403046400。','Gram determinant=1526509670400. Volume²=det(G)/36=42403046400.'],
['面の三角形条件と行列の主小行列式の非負性を、分数で厳密判定。','The face triangle inequalities and non-negativity of the principal minors are tested exactly with fractions.'],
['図は斜めからの正投影。長さや角度を画面上で測った値とは異なります。','The diagram is an oblique orthographic projection; on-screen lengths and angles are not the calculated geometric values.'],
['存在条件・体積の二乗を厳密判定','Exact test of existence conditions and volume squared'],
['1・2・4・5・6・12・13・16・17・18・19・21・25・28・29','1, 2, 4, 5, 6, 12, 13, 16, 17, 18, 19, 21, 25, 28, 29'],
['全30人から15人を残す','Leave 15 of 30 people'],
['取り除く順','Order removed'],
['番号','Number'],
['開始番号を1として数え、指定した数番目を取り除きます。','Count the starting position as 1 and remove the person at the specified count.'],
['次の人から再び1と数えます。残った番号は元の番号順に表示します。','Resume the count at one with the next person. Survivors are displayed in their original numerical order.'],
['残す人数に達したところで停止します。','Stop when the requested number of people remains.'],
['整数で順序を計算','Integer calculation of the elimination order'],
['人数は2〜200の整数にしてください。','Enter an integer from 2 to 200 for the number of people.'],
['6×6の方陣：どの縦・横・二本の対角線もこの和','6×6 magic square: every row, column, and main diagonal has this sum'],
['行','Row'],
['1列','Column 1'],['2列','Column 2'],['3列','Column 3'],['4列','Column 4'],['5列','Column 5'],['6列','Column 6'],
['1から36までを一度ずつ配置。','Place each integer from 1 through 36 exactly once.'],
['奇数の小方陣を四つ並べ、一部の列を交換。','Arrange four odd-order subsquares and exchange selected columns.'],
['すべての行・列・二本の対角線と、数の重複がないことを照合済み。','Every row, column, and main diagonal has been checked, along with the absence of duplicate entries.'],
['整数で全方向を検算','Exact integer checks in every direction'],
['一辺のマス数は3〜16の整数にしてください。','Enter an integer from 3 to 16 for the number of cells per side.'],
['目標の地面から頂点までの高さ','Height from the target’s base to its top'],
['近い地点から目標の足まで','From the nearer station to the target’s base'],
['遠い地点から目標の足まで','From the farther station to the target’s base'],
['目の高さから頂点まで','From eye level to the target’s top'],
['目標の高さ','Target height'],
['近い地点からの水平距離 x = 基線 × 遠い傾き ÷ (近い傾き − 遠い傾き)。','Horizontal distance from the nearer station x = baseline × farther slope ÷ (nearer slope − farther slope).'],
['高さ = x × 近い傾き + 目の高さ。','Height = x × nearer slope + eye height.'],
['遠い地点から見た傾きにも戻して照合済み。','The result is also checked by substituting it into the slope from the farther station.'],
['二地点の関係を分数で照合','Exact fractional check using the two stations'],
['分母 100 以下で、入力した数との差が最小','Closest value to the input with denominator at most 100'],
['商','Partial quotient'],
['収束分数','Convergent'],
['入力値との絶対差','Absolute error from the input'],
['連分数の商：[3, 7, 15]（上限に達した段まで）','Continued-fraction quotients: [3, 7, 15] (through the stage at which the bound is reached)'],
['最後の収束分数と中間分数を、誤差の交差積で比較。','Compare the last convergent and the intermediate fraction by cross-multiplying their errors.'],
['誤差が同じなら分母が小さい方、さらに同じなら小さい数を採用。','If the errors are equal, choose the smaller denominator; if those are also equal, choose the smaller value.'],
['入力値との差：17672705389530607801694944621/99000000000000000000000000000000','Difference from the input: 17672705389530607801694944621/99000000000000000000000000000000'],
['分数で誤差を厳密比較','Exact comparison of errors as fractions'],
['近似する数は80文字以内の整数・小数・分数にしてください。','Enter the value to approximate as an integer, decimal, or fraction of no more than 80 characters.'],
['8・15・17','8, 15, 17'],
['短い直角辺・長い直角辺・斜辺','Shorter leg, longer leg, and hypotenuse'],
['短い直角辺','Shorter leg'],
['長い直角辺','Longer leg'],
['斜辺','Hypotenuse'],
['三辺の最大公約数','Greatest common divisor of the three sides'],
['原始三つ組','Primitive triple'],
['2mn、m²−n²、m²+n²から三辺を構成。','Construct the three sides as 2mn, m²−n², and m²+n².'],
['三辺に同じ正整数の倍率を掛けます。','Multiply all three sides by the same positive integer scale factor.'],
['直角を挟む二辺の平方和と斜辺の平方が一致することを照合済み。','The sum of the squares of the two legs is verified to equal the square of the hypotenuse.'],
['大きな整数も厳密計算','Exact calculation, including large integers'],
['大きい数 mは1〜1000000000の整数にしてください。','Enter the larger parameter m as an integer from 1 to 1,000,000,000.'],
['自己交差しない多角形の面積','Area of a non-self-intersecting polygon'],
['頂点','Vertex'],
['座標 (x, y)','Coordinates (x, y)'],
['隣の頂点との交差積','Cross product with the next vertex'],
['符号付き面積の2倍：14','Twice the signed area: 14'],
['面積重心 = (19/14, 19/14)。一様な厚さ・密度の図形を想定。','Area centroid = (19/14, 19/14), assuming uniform thickness and density.'],
['頂点の順を逆にしても、面積と重心は変わりません。','Reversing the order of the vertices leaves the area and centroid unchanged.'],
['面積・重心を分数で厳密計算','Exact fractional calculation of area and centroid'],
['入力は全体1400文字以内にしてください。','Keep the complete input within 1,400 characters.'],
['二つの平面にはさまれた球内の体積','Volume of the part of a sphere between two planes'],
['体積','Volume'],
['球面の曲面積（端面を除く）','Curved surface area of the sphere (excluding the end faces)'],
['一様な立体の重心 z','Centroid z of the uniform solid'],
['下端の円の半径の二乗','Squared radius of the lower circular section'],
['上端の円の半径の二乗','Squared radius of the upper circular section'],
['球の中心を z=0、上向きを正とします。','Take the sphere’s center as z=0, with positive z upward.'],
['断面積 π(R²−z²) を下側から上側まで積分。','Integrate the cross-sectional area π(R²−z²) from the lower plane to the upper plane.'],
['重心は z を掛けた断面積の積分を、体積で割って求めます。','Find the centroid by integrating z times the cross-sectional area and dividing by the volume.'],
['πの係数と重心を厳密計算','Exact coefficient of π and exact centroid'],
['円の内部を一周回転させた環体の体積','Volume of the torus formed by revolving the disk once'],
['表面積','Surface area'],
['外側の半径','Outer radius'],
['内側の半径','Inner radius'],
['断面積 πr² と、断面中心が進む長さ 2πR を掛けます。','Multiply the cross-sectional area πr² by the distance 2πR traveled by its center.'],
['表面積は断面の円周 2πr × 2πR。','The surface area is the cross-sectional circumference 2πr times 2πR.'],
['R>r：中央に穴のある環体です。','R>r: this is a ring torus with a central hole.'],
['π²の係数を厳密計算','Exact calculation of the coefficient of π²'],
['36・56.25・64','36, 56.25, 64'],
['頂点 A・B・C に対応する三円の半径（近似）','Approximate radii of the three circles associated with vertices A, B, and C'],
['中心 (x, y)','Center (x, y)'],
['A=(0,0)、B=(252,0)、Cは上側に配置。','Place A=(0,0), B=(252,0), and C above the baseline.'],
['内接円と角の二等分線を使い、三円の半径と中心を構成。','Construct the radii and centers of the three circles from the incircle and the angle bisectors.'],
['互いの外接・各円と二辺の接触を距離で検算。最大相対残差：3.33e-16','Check mutual external tangency and each circle’s tangency to two sides by distance. Maximum relative residual: 3.33e-16'],
['三円の合計面積を最大にする問題とは異なります。','This is not the problem of maximizing the total area of the three circles.'],
['円同士と二辺への接触を近似検算','Numerical check of circle-to-circle and circle-to-side tangencies'],
['8 個','8 solutions'],
['内接・外接の組合せを含む正の半径の解','Positive-radius solutions including internal and external tangencies'],
['中心 (x, y) の近似','Approximate center (x, y)'],
['半径（近似・一部は厳密値）','Radius (approximate; exact for selected entries)'],
['円1の中心からの差 (Δx, Δy)','Offset from the center of circle 1 (Δx, Δy)'],
['円1との接触','Tangency to circle 1'],
['円2との接触','Tangency to circle 2'],
['円3との接触','Tangency to circle 3'],
['外接','External'],
['入力円を包む','Encloses the input circle'],
['表の小数は近似です。丸めると内接の向きが読めなくなる場合のみ、半径を厳密な有限小数・分数で示します。','Decimals in the table are approximate. A radius is shown as an exact terminating decimal or fraction only when rounding would obscure the orientation of an internal tangency.'],
['差の原点は円1の中心 (0, 0)。大きな座標中の小さなずれは、差の列を使ってください。','Offsets are measured from the center of circle 1 at (0, 0). Use the offset column to read small displacements within large coordinates.'],
['接触距離 |ρ + σᵢrᵢ| を8通りの符号で調べます。','Evaluate the tangency distance |ρ + σᵢrᵢ| for all eight sign combinations.'],
['円の方程式を引き算し、中心を半径の一次式として表した後、二次方程式を解きます。','Subtract the circle equations, express the center as a linear function of the radius, and solve the resulting quadratic.'],
['二乗する前の距離式で全解を再検算。最大相対残差：2.89e-16','Recheck every solution in the unsquared distance equations. Maximum relative residual: 2.89e-16'],
['表はすべての解。図は入力した三円と、表の1番の解を同じ尺度で表示します。','The table lists every solution. The diagram shows the three input circles and solution 1 at the same scale.'],
['接触の符号と距離を検算','Checks of tangency signs and distances'],
['P(1) ／ 次数 3','P(1) / degree 3'],
['各点の値と傾きを満たす基底多項式を組み立て、重み付きで足します。','Construct basis polynomials satisfying the value and slope conditions at each point, then add them with the appropriate weights.'],
['全2点の値と傾きを元の条件へ再代入し、一致を確認。','Substitution verifies the values and slopes at both input points.'],
['全条件を分数で照合','Exact fractional check of every condition'],
['条件は全体1400文字以内で入力してください。','Keep all conditions together within 1,400 characters.'],
['同じ重複度の因子をまとめた分解','Factorization grouped by multiplicity'],
['最高次係数1の因子','Monic factor'],
['元の最高次係数：1','Original leading coefficient: 1'],
['fとf′の共通因子を取り、重複度ごとに分けます。','Use common factors of f and f′ to separate factors by multiplicity.'],
['積を展開し直し、元の全係数と一致することを確認。','Expand the product again and verify every original coefficient.'],
['各因子に重根がなく、異なる群の因子どうしが互いに素であることも照合。','Also verify that each factor is square-free and that factors in different multiplicity groups are pairwise coprime.'],
['有理数係数で厳密分解','Exact factorization over the rationals'],
['8次までの合成逆 g(x)','Compositional inverse g(x) through degree 8'],
['f(g(x))の低い次数から、未知の係数を一つずつ決めます。','Determine the unknown coefficients one at a time, beginning with the lowest degree in f(g(x)).'],
['f(g(x)) と g(f(x)) が、ともに 8次まで x と一致することを確認。','Verify that both f(g(x)) and g(f(x)) agree with x through degree 8.'],
['表示していない高次の項は残ります。数値としての収束範囲はここでは判定しません。','Unshown higher-order terms remain. This calculation does not determine the numerical domain of convergence.'],
['両方向の合成を厳密照合','Exact verification of composition in both directions'],
['t = 2cos(2π/17) の最小多項式 ／ 次数 8','Minimal polynomial of t = 2cos(2π/17) / degree 8'],
['z^17−1 から、真の約数に対応する円分多項式を順に割って Φ_17 を構成。','Construct Φ_17 from z^17−1 by successively dividing out the cyclotomic polynomials corresponding to proper divisors.'],
['対称な係数を t=z+1/z の多項式へ変換。','Convert the symmetric coefficients into a polynomial in t=z+1/z.'],
['z^8 Ψ(z+1/z) = Φ_17(z) を展開し、全係数が一致することを確認。','Expand z^8 Ψ(z+1/z) = Φ_17(z) and verify that every coefficient agrees.'],
['この次数は現代の実円分体の次数です。史料の「定乗数」とは区別します。','This is the degree of the modern maximal real cyclotomic subfield; it should not be confused with the historical term teijōsū.'],
['整数係数で恒等式を検算','Identity verified over the integers'],
['円を分ける数 nは3〜60の整数にしてください。','Enter the number n of circle divisions as an integer from 3 to 60.'],
['指定した二つの関係を満たす箱の最大体積（近似）','Maximum volume of a box satisfying the two specified relations (approx.)'],
['高さ','Height'],
['最大体積','Maximum volume'],
['幅をwとすると、長さ=w+D、高さ=S−w。','With width w, length=w+D and height=S−w.'],
['V′(w)=−3w²+2(S−D)w+SD=0の正の根を選びます。','Choose the positive root of V′(w)=−3w²+2(S−D)w+SD=0.'],
['両端で体積0、区間内の停留点は一つなので、ここで最大。','The volume is zero at both endpoints and there is only one stationary point in the interval, so this point gives the maximum.'],
['微分条件と寸法の関係を検算','Check of the derivative condition and dimensional relations'],
['長さと幅の差は24文字以内の整数・小数・分数にしてください。','Enter the difference between length and width as an integer, decimal, or fraction of no more than 24 characters.'],
['56・31.5・41.1428571・24.8888889','56, 31.5, 41.1428571, 24.8888889'],
['頂点A・B・Cの円と、底辺BCに接する第4円（近似）','Circles at vertices A, B, and C, together with a fourth circle tangent to base BC (approx.)'],
['中心 (x,y)','Center (x,y)'],
['内','Internal'],
['B=(0,0)、C=(a,0)、Aは上側。','Place B=(0,0), C=(a,0), and A above the base.'],
['史料研究の二次式を同値変形し、頂点Aの円の候補を求めます。','Rearrange the quadratic reported in the historical study into an equivalent form to obtain candidates for the circle at vertex A.'],
['A円はB円・C円・第4円に接触。第4円は底辺BCと三円に接触。B円とC円は離れています。','Circle A is tangent to circles B, C, and the fourth circle. The fourth circle is tangent to base BC and all three vertex circles. Circles B and C do not touch.'],
['二次式の候補をすべて調べ、五つの円同士の接触と七つの辺への接触を検算。','Test every candidate from the quadratic and check all five circle-to-circle tangencies and seven circle-to-side tangencies.'],
['最大相対残差：7.77e-16。成立した配置：1組。','Maximum relative residual: 7.77e-16. Valid configurations: 1.'],
['安島の四円配置を接触条件で検算','Ajima’s four-circle configuration checked against the tangency conditions'],
['二つの楕円が入る三角形の高さ','Height of a triangle containing two ellipses'],
['底辺の全長（近似）','Total base length (approx.)'],
['この短軸で最小となる軸比','Axis ratio that minimizes the height for this minor-axis length'],
['最小の高さ','Minimum height'],
['短軸の全長をq、長軸/短軸をkとします。','Let q be the full minor axis and k the ratio of major axis to minor axis.'],
['H−4q=q(k−2)²/(k−1)≥0。k=2で最小です。','H−4q=q(k−2)²/(k−1)≥0, so the minimum occurs at k=2.'],
['上下の楕円と両等辺の接触を支持関数で検算。','Use support functions to check the tangency of the upper and lower ellipses to the two equal sides.'],
['高さと最小条件を厳密計算','Exact height and minimizing condition'],
['円の中心から測った、左から順の切断位置','Cut positions from left to right, measured from the circle’s center'],
['切断','Cut'],
['位置 x（近似）','Position x (approx.)'],
['左側の目標面積 / 全体','Target area to the left / total area'],
['再積分した割合（近似）','Ratio obtained by reintegration (approx.)'],
['切断線は互いに平行な鉛直線。円の中心はx=0です。','The cuts are parallel vertical lines, and the circle is centered at x=0.'],
['円弧を積分した面積を、累積した面積比と照合して二分法で逆算。','Invert the cumulative area ratio by bisection, using the integrated area under the circular arc.'],
['各領域の目標面積は、入力した比に比例します。','Each target region has area proportional to the ratio entered.'],
['割合の最大絶対残差：5.55e-17','Maximum absolute residual in the ratios: 5.55e-17'],
['面積比を再積分して検算','Check by reintegrating the area ratios'],
['524173・524174・524175','524173, 524174, 524175'],
['10番目の連続する整数三辺','Tenth triangle with consecutive integer side lengths'],
['順','Index'],
['短い辺','Shortest side'],
['中間の辺','Middle side'],
['長い辺','Longest side'],
['整数の面積','Integer area'],
['三辺をm−1,m,m+1とすると、16A²=3m²(m²−4)。','For sides m−1, m, and m+1, 16A²=3m²(m²−4).'],
['m=2x、x²−3y²=1のとき、面積A=3xyは整数。','When m=2x and x²−3y²=1, the area A=3xy is an integer.'],
['(x,y)=(1,0)から、次の組を(2x+3y,x+2y)で作ります。','Starting from (x,y)=(1,0), generate the next pair as (2x+3y,x+2y).'],
['各組のPell方程式とHeronの面積式を整数で再検算。','For every pair, recheck the Pell equation and Heron’s area formula using integers.'],
['整数三辺と整数面積を厳密照合','Exact verification of integer sides and integer area'],
['求める組数は1〜100の整数にしてください。','Enter the number of triples required as an integer from 1 to 100.'],
['指定した傾きに対応する第2の点','Second point corresponding to the specified slope'],
['式','Expression'],
['分子 / 共通分母','Numerator / common denominator'],
['共通分母','Common denominator'],
['基準点を通る直線 y−y₀=t(x−x₀) を代入。','Substitute the line y−y₀=t(x−x₀) through the base point.'],
['既知の交点に対応する因子を除き、第2の交点を求めます。','Remove the factor corresponding to the known intersection and solve for the second intersection.'],
['媒介式を二次曲線へ戻す恒等式を、全係数で照合済み。','The identity obtained by substituting the parametrization back into the conic has been checked coefficient by coefficient.'],
['有理媒介と交点を厳密検算','Exact verification of the rational parametrization and intersection'],
['係数は全体1400文字以内で入力してください。','Keep the complete coefficient input within 1,400 characters.'],
['2個の交点','2 intersection points'],
['円と放物線の全実交点。小数は近似値。厳密な範囲は分数の区間で確認できます。','All real intersections of the circle and parabola. Decimals are approximate; exact ranges are given by rational intervals.'],
['交点','Intersection'],
['x の目安','Approximate x'],
['y の目安','Approximate y'],
['x の厳密区間','Exact interval for x'],
['y の厳密上下界','Exact bounds for y'],
['y=ax²+bx+cを円の式へ代入。','Substitute y=ax²+bx+c into the equation of the circle.'],
['得られた多項式：x^4 + x^2 − 1','Resulting polynomial: x^4 + x^2 − 1'],
['Sturm列で全実根を分離し、区間演算でyの範囲を求めます。','Use a Sturm sequence to isolate every real root, then interval arithmetic to bound y.'],
['この置換では各実数xに一つの実数yが対応します。重複度は消去した式での値です。','Under this substitution, each real x determines one real y. Multiplicity refers to the eliminated polynomial.'],
['全実根を有理数区間で認証','All real roots certified by rational intervals'],
['二次係数は24文字以内の整数・小数・分数にしてください。','Enter the quadratic coefficient as an integer, decimal, or fraction of no more than 24 characters.'],
['最小 -2 ～ -2 ／ 最大 2 ～ 2','Minimum −2 to −2 / maximum 2 to 2'],
['閉区間全体の最小値・最大値。小数は目安、厳密区間は途中式に表示。','Minimum and maximum over the entire closed interval. Decimals are guides; exact intervals appear in the calculation steps.'],
['候補','Candidate'],
['x の区間','Interval for x'],
['値の厳密な上下界','Exact bounds for the value'],
['停留点の候補','Stationary-point candidate'],
['導関数：3·x^2 − 3','Derivative: 3·x^2 − 3'],
['端点と導関数の全実根を調べます。','Evaluate the endpoints and every real root of the derivative.'],
['最小値の厳密区間：-89202980794122967935117958676619007287623679/44601490397061246283071436545296723011960832 ～ -2','Exact interval for the minimum: -89202980794122967935117958676619007287623679/44601490397061246283071436545296723011960832 to -2'],
['最大値の厳密区間：2 ～ 89202980794122967935117958676619007287623679/44601490397061246283071436545296723011960832','Exact interval for the maximum: 2 to 89202980794122967935117958676619007287623679/44601490397061246283071436545296723011960832'],
['小数の表示が同じでも、厳密値かどうかは分数の上下界で確認できます。','Even when the decimal displays agree, the fractional bounds show whether the value is exact.'],
['端点・停留点と区間演算','Endpoints, stationary points, and interval arithmetic'],
['左が下界、右が上界。区間全体を含む厳密な範囲。','The left value is the lower bound and the right value the upper bound; together they give an exact enclosure over the whole interval.'],
['下界','Lower bound'],
['上界','Upper bound'],
['区間を0〜1に移し、Bernstein基底の係数へ変換。','Map the interval to 0–1 and convert to coefficients in the Bernstein basis.'],
['非負で総和1の基底なので、関数の値は係数の最小値と最大値の間に入ります。','Because the basis functions are non-negative and sum to 1, the function lies between the smallest and largest coefficients.'],
['二等分を繰り返し、各区間の係数をde Casteljau法で厳密に更新。','Bisect repeatedly, updating the coefficients on each subinterval exactly by de Casteljau’s algorithm.'],
['この上下界は安全な包み込みです。分割が有限なので、真の最小値・最大値と一致するとは限りません。','These bounds are a certified enclosure. Because the subdivision is finite, they need not equal the true minimum and maximum.'],
['区間全体を分数で包み込む','Exact fractional enclosure over the entire interval'],
['多項式部分と、各極に対応する部分分数','Polynomial part and partial fractions for each pole'],
['根 r','Root r'],
['分母 (x−r) の指数','Exponent of (x−r) in the denominator'],
['分子の係数','Numerator coefficient'],
['分母：x^3 − x^2 − x + 1','Denominator: x^3 − x^2 − x + 1'],
['まず多項式の割り算で商と真分数に分離。','First use polynomial division to separate the quotient from the proper fraction.'],
['共通分母を掛けた係数方程式を解き、元の分子の全係数を再現。','Multiply through by the common denominator, solve the coefficient equations, and reproduce every coefficient of the original numerator.'],
['元の分母が0になる点では、式は定義されません。','The expression is undefined wherever the original denominator is zero.'],
['分数を合成し直して厳密照合','Exact verification by recombining the fractions'],
['初期項','Initial term'],
['係数（法を指定した場合はその余り）','Coefficient (reduced modulo the modulus, if specified)'],
['a(n)=c₁a(n−1)+…+c_d a(n−d)。初期値はa(0)から。','a(n)=c₁a(n−1)+…+c_d a(n−d), with initial values beginning at a(0).'],
['x^d=c₁x^(d−1)+…+c_dを使って、多項式の積をd次未満へ戻します。','Use x^d=c₁x^(d−1)+…+c_d to reduce polynomial products to degree less than d.'],
['二乗を繰り返し、x^nの余りを約log₂(n)段階で計算。','Repeated squaring computes the remainder of x^n in about log₂(n) stages.'],
['結果は初期値の線形結合です。','The result is a linear combination of the initial values.'],
['整数の厳密計算','Exact integer calculation'],
['xの10次までの形式的な級数','Formal power series through degree 10 in x'],
['定数項g₀=1から係数を順に求めます。','Determine the coefficients in order, beginning with the constant term g₀=1.'],
['F g′=α F′g の全係数を指定次数まで照合済み。','Every coefficient in F g′=α F′g has been verified through the requested degree.'],
['形式的な級数です。数値を代入したときの収束は別途確認が必要です。','This is a formal power series; convergence after substituting a numerical value must be considered separately.'],
['分数による係数計算・恒等式の検算','Fractional coefficient calculation and exact identity check'],
['F(0,y₀)=0、Fᵧ(0,y₀)≠0を厳密に確認。','Verify exactly that F(0,y₀)=0 and Fᵧ(0,y₀)≠0.'],
['n次の未定係数に掛かる係数は常にFᵧ(0,y₀)。既知の低次係数から順に解きます。','The coefficient multiplying the unknown nth-order term is always Fᵧ(0,y₀). Solve successively from the known lower-order coefficients.'],
['F(x,y(x)) の0〜10次がすべて0になることを検算済み。','Verified that every coefficient of F(x,y(x)) from degree 0 through 10 is zero.'],
['指定した初期値から出る一つの形式的な枝です。ほかの枝や収束半径は求めません。','This is one formal branch determined by the specified initial value. Other branches and the radius of convergence are not computed.'],
['項は1400文字以内で入力してください。','Keep the term input within 1,400 characters.'],
['分子・分母の定数項から係数を表示します','Coefficients are listed from the constant terms of the numerator and denominator upward'],
['係数（定数項→高次）','Coefficients (constant term to higher degree)'],
['分子 P','Numerator P'],
['分母 Q','Denominator Q'],
['入力した級数の打切り値','Truncated value of the input series'],
['Q(0)=1とし、Qf−Pの4次までの係数を0にします。','Set Q(0)=1 and make the coefficients of Qf−P vanish through degree 4.'],
['分母係数の一次方程式を分数で解き、全係数を再照合。','Solve the linear equations for the denominator coefficients over the rationals, then recheck every coefficient.'],
['入力された有限個の係数への一致です。元の関数の収束・誤差や、特定の値での近似精度は保証しません。','The agreement is with the finite list of coefficients supplied. It does not guarantee convergence or error bounds for the original function, or accuracy at any particular value.'],
['指定した有理数の点で、P/Qを分数で評価。','Evaluate P/Q exactly as a fraction at the specified rational point.'],
['Padéの係数条件を厳密照合','Exact verification of the Padé coefficient conditions'],
['右の円の半径を入力してください。','Enter the radius of the circle on the right.'],
['小数点以下の桁数を入力してください。','Enter the number of decimal places.'],
['区間の左端を入力してください。','Enter the left endpoint of the interval.'],
['区間の右端を入力してください。','Enter the right endpoint of the interval.'],
['区間の許容幅を入力してください。','Enter the permitted interval width.'],
['2行目の条件が、それまでの条件と矛盾しています。共通する整数解はありません。','Condition 2 conflicts with the preceding conditions; there is no common integer solution.'],
['累乗 pを入力してください。','Enter the power p.'],
['足の数は80桁以内の0以上の整数で入力してください。','Enter the number of legs as a non-negative integer of no more than 80 digits.'],
['余る数は80桁以内の0以上の整数で入力してください。','Enter the surplus as a non-negative integer of no more than 80 digits.'],
['多い配り方は80桁以内の0以上の整数で入力してください。','Enter the larger per-person share as a non-negative integer of no more than 80 digits.'],
['足りない数は80桁以内の0以上の整数で入力してください。','Enter the deficit as a non-negative integer of no more than 80 digits.'],
['増える倍率は3桁以内の0以上の整数で入力してください。','Enter the multiplier as a non-negative integer of no more than 3 digits.'],
['回数は3桁以内の0以上の整数で入力してください。','Enter the number of steps as a non-negative integer of no more than 3 digits.'],
['到達できません','No solution is reachable'],
['到達可能な状態を調べ終えました。','Every reachable state has been examined.'],
['容器Bは3桁以内の0以上の整数で入力してください。','Enter the capacity of container B as a non-negative integer of no more than 3 digits.'],
['容器Cは3桁以内の0以上の整数で入力してください。','Enter the capacity of container C as a non-negative integer of no more than 3 digits.'],
['量りたい量は3桁以内の0以上の整数で入力してください。','Enter the target amount as a non-negative integer of no more than 3 digits.'],
['股 bは30文字以内の正の小数で入力してください。','Enter leg b as a positive decimal of no more than 30 characters.'],
['辺 bは30文字以内の正の小数で入力してください。','Enter side b as a positive decimal of no more than 30 characters.'],
['辺 cは30文字以内の正の小数で入力してください。','Enter side c as a positive decimal of no more than 30 characters.'],
['立方すると入力値に一致します。','Cubing the result reproduces the input exactly.'],
['小数点以下の桁数は3桁以内の0以上の整数で入力してください。','Enter the number of decimal places as a non-negative integer of no more than 3 digits.'],
['共通因子があり、この消去式だけでは x を絞れません。','The equations have a common factor, so this eliminant alone does not restrict x.'],
['表示する小数桁は0〜12の整数にしてください。','Enter an integer from 0 to 12 for the number of displayed decimal places.'],
['項数は1〜120の整数にしてください。','Enter an integer from 1 to 120 for the number of terms.'],
['接する直線','Tangent line'],
['直線','Line'],
['表示する解は1〜2の整数にしてください。','Choose solution 1 or 2.'],
['見る向きは0〜360の整数にしてください。','Enter the viewing angle as an integer from 0 to 360.'],
['開始角は0〜360度の小数にしてください。','Enter the starting angle as a decimal from 0 to 360 degrees.'],
['累乗 pは0〜40の整数にしてください。','Enter the power p as an integer from 0 to 40.'],
['区間は0からπ/2。被積分関数は sin^p θ cos^q θ。','The interval is 0 to π/2, and the integrand is sin^p θ cos^q θ.'],
['p≥2 なら J(p,q)=(p−1)J(p−2,q)/(p+q)。q側にも同じ漸化式があります。','For p≥2, J(p,q)=(p−1)J(p−2,q)/(p+q). The same recurrence applies in the q direction.'],
['両指数が偶数の場合だけ、有理数×π の形になります。これは円理表につながる現代的な変数変換です。','The result is a rational multiple of π only when both exponents are even. This is a modern change of variables related to the structure of enri tables.'],
['指数 pは0〜40の整数にしてください。','Enter the exponent p as an integer from 0 to 40.'],
['指数 qは0〜40の整数にしてください。','Enter the exponent q as an integer from 0 to 40.'],
['円になった場合の厳密な周長','Exact circumference in the circular case'],
['πを含む厳密値','Exact value involving π'],
['級数の項数は1〜1000の整数にしてください。','Enter the number of series terms as an integer from 1 to 1000.'],
['同じ半径の直交二円柱の共通体積','Common volume of two perpendicular cylinders of equal radius'],
['断面積は 4(r²−z²)。−r から r まで積分すると16r³/3。','The cross-sectional area is 4(r²−z²); integrating from −r to r gives 16r³/3.'],
['有理数の厳密値','Exact rational value'],
['実根へ渡せるのは1〜8次、各整数係数の絶対値10¹⁸以下。範囲外でも消去式そのものは厳密値です。','Only degree 1–8 polynomials with integer coefficients of absolute value at most 10¹⁸ can be sent to the real-root tool. Outside that range, the eliminant itself remains exact.'],
['原点を通る円は直線へ移ります。','A circle through the origin maps to a line.'],
['反転後の直線','Inverted line'],
['原点なので定義されません','Undefined at the origin'],
['最後の接触、戻り位置、重なりを途中式で確認できます。','Open the working to inspect the final tangency, return position, and overlaps.'],
['この個数の閉鎖は角度・距離の小数検算です。厳密な等式の証明とは区別します。','Closure for this number of circles is checked numerically by angles and distances; this is distinct from an exact equality proof.'],
['角度・中心・半径による数値判定','Numerical test using angles, centers, and radii'],
['つなぐ円の個数は3〜24の整数にしてください。','Enter the number of chain circles as an integer from 3 to 24.'],
['式は2〜6行にしてください。','Enter between 2 and 6 equations.'],
['自由変数 1個','1 free variable'],
['解はありません','No solution'],
['重根があります（複素数の重根も含む）。','A repeated root was detected. This test also detects non-real repeated roots.'],
['最後の累乗は1〜30の整数にしてください。','Enter the final power as an integer from 1 to 30.'],
['指定した小数で厳密に一致。','Exact at the requested decimal precision.'],
['開く次数は2〜20の整数にしてください。','Enter the root degree as an integer from 2 to 20.'],
['小数桁は0〜40の整数にしてください。','Enter the number of decimal places as an integer from 0 to 40.'],
['移す量 hは24文字以内の整数・小数・分数にしてください。','Enter the shift h as an integer, decimal, or fraction of no more than 24 characters.'],
['打ち切る次数は0〜30の整数にしてください。','Enter the truncation degree as an integer from 0 to 30.'],
['弧の高さは24文字以内の整数・小数・分数にしてください。','Enter the sagitta as an integer, decimal, or fraction of no more than 24 characters.'],
['分割数は16〜4096の整数にしてください。','Enter the number of subdivisions as an integer from 16 to 4096.'],
['開始角は24文字以内の整数・小数・分数にしてください。','Enter the starting angle as an integer, decimal, or fraction of no more than 24 characters.'],
['終了角は24文字以内の整数・小数・分数にしてください。','Enter the ending angle as an integer, decimal, or fraction of no more than 24 characters.'],
['左端は24文字以内の整数・小数・分数にしてください。','Enter the left endpoint as an integer, decimal, or fraction of no more than 24 characters.'],
['右端は24文字以内の整数・小数・分数にしてください。','Enter the right endpoint as an integer, decimal, or fraction of no more than 24 characters.'],
['連ねる円の個数は1〜100の整数にしてください。','Enter the number of circles in the chain as an integer from 1 to 100.'],
['平面に退化しています。厚みのある四面体ではありません。','The configuration is planar; it is not a tetrahedron with positive volume.'],
['最後の番号は漸化式でも照合済み。','The final number has also been verified by the recurrence.'],
['数える数は1〜1000000000000の整数にしてください。','Enter the counting step as an integer from 1 to 1,000,000,000,000.'],
['開始番号は1〜30の整数にしてください。','Enter the starting number as an integer from 1 to 30.'],
['残す人数は1〜30の整数にしてください。','Enter the number of survivors as an integer from 1 to 30.'],
['奇数の方陣を斜めの移動と折り返しで構成。','Construct the odd-order square by diagonal movement with wraparound.'],
['4の倍数の方陣を補数の置換で構成。','Construct the doubly even square by replacing selected entries with their complements.'],
['目の高さは24文字以内の整数・小数・分数にしてください。','Enter the eye height as an integer, decimal, or fraction of no more than 24 characters.'],
['分母の上限は1〜1000000000000の整数にしてください。','Enter the denominator bound as an integer from 1 to 1,000,000,000,000.'],
['20・21・29','20, 21, 29'],['12・16・20','12, 16, 20'],['3・4・5','3, 4, 5'],
['小さい数 nは1〜1000000000の整数にしてください。','Enter the smaller parameter n as an integer from 1 to 1,000,000,000.'],
['倍率は1〜1000000000の整数にしてください。','Enter the scale factor as an integer from 1 to 1,000,000,000.'],
['3〜31行で入力してください。','Enter between 3 and 31 rows.'],
['下側の高さは24文字以内の整数・小数・分数にしてください。','Enter the lower height as an integer, decimal, or fraction of no more than 24 characters.'],
['上側の高さは24文字以内の整数・小数・分数にしてください。','Enter the upper height as an integer, decimal, or fraction of no more than 24 characters.'],
['R=r：中央の穴が一点に閉じる場合です。','R=r: the central hole closes to a single point.'],
['0.751999353・0.664894189・0.507933962','0.751999353, 0.664894189, 0.507933962'],
['0.366025404・0.366025404・0.366025404','0.366025404, 0.366025404, 0.366025404'],
['3〜3行で入力してください。','Enter exactly 3 rows.'],
['条件は2〜6行で入力してください。','Enter between 2 and 6 conditions.'],
['求める位置は24文字以内の整数・小数・分数にしてください。','Enter the target position as an integer, decimal, or fraction of no more than 24 characters.'],
['打ち切る次数は1〜20の整数にしてください。','Enter the truncation degree as an integer from 1 to 20.'],
['0.442380608・0.295107335・0.295107335・0.202454492','0.442380608, 0.295107335, 0.295107335, 0.202454492'],
['0.843029555・0.552796387・0.363606481・0.32312025','0.843029555, 0.552796387, 0.363606481, 0.32312025'],
['長軸と短軸の比は24文字以内の整数・小数・分数にしてください。','Enter the major-to-minor axis ratio as an integer, decimal, or fraction of no more than 24 characters.'],
['39571031999226139563162735373・39571031999226139563162735374・39571031999226139563162735375','39571031999226139563162735373, 39571031999226139563162735374, 39571031999226139563162735375'],
['51・52・53','51, 52, 53'],
['基準点xは24文字以内の整数・小数・分数にしてください。','Enter the base point’s x-coordinate as an integer, decimal, or fraction of no more than 24 characters.'],
['基準点yは24文字以内の整数・小数・分数にしてください。','Enter the base point’s y-coordinate as an integer, decimal, or fraction of no more than 24 characters.'],
['傾きは24文字以内の整数・小数・分数にしてください。','Enter the slope as an integer, decimal, or fraction of no more than 24 characters.'],
['一次係数は24文字以内の整数・小数・分数にしてください。','Enter the linear coefficient as an integer, decimal, or fraction of no more than 24 characters.'],
['定数項は24文字以内の整数・小数・分数にしてください。','Enter the constant term as an integer, decimal, or fraction of no more than 24 characters.'],
['円の中心xは24文字以内の整数・小数・分数にしてください。','Enter the circle center’s x-coordinate as an integer, decimal, or fraction of no more than 24 characters.'],
['円の中心yは24文字以内の整数・小数・分数にしてください。','Enter the circle center’s y-coordinate as an integer, decimal, or fraction of no more than 24 characters.'],
['半径は24文字以内の整数・小数・分数にしてください。','Enter the radius as an integer, decimal, or fraction of no more than 24 characters.'],
['区間の左端は24文字以内の整数・小数・分数にしてください。','Enter the interval’s left endpoint as an integer, decimal, or fraction of no more than 24 characters.'],
['区間の右端は24文字以内の整数・小数・分数にしてください。','Enter the interval’s right endpoint as an integer, decimal, or fraction of no more than 24 characters.'],
['分割の深さは0〜7の整数にしてください。','Enter the subdivision depth as an integer from 0 to 7.'],
['因子の入力は600文字以内にしてください。','Keep the factor input within 600 characters.'],
['項番号は0〜1兆の整数にしてください。','Enter the term index as an integer from 0 to 1,000,000,000,000.'],
['法は0〜10の18乗の整数にしてください。','Enter the modulus as an integer from 0 to 1,000,000,000,000,000,000.'],
['指数は24文字以内の整数・小数・分数にしてください。','Enter the exponent as an integer, decimal, or fraction of no more than 24 characters.'],
['次数は1〜20の整数にしてください。','Enter the degree as an integer from 1 to 20.'],
['次数は1〜16の整数にしてください。','Enter the degree as an integer from 1 to 16.'],
['各行にxの指数、yの指数、係数を入力してください。','On each row, enter the exponent of x, the exponent of y, and the coefficient.'],
['初期値は24文字以内の整数・小数・分数にしてください。','Enter the initial value as an integer, decimal, or fraction of no more than 24 characters.'],
['分子の次数は0〜8の整数にしてください。','Enter the numerator degree as an integer from 0 to 8.'],
['分母の次数は0〜8の整数にしてください。','Enter the denominator degree as an integer from 0 to 8.'],
['代入する値は24文字以内の整数・小数・分数にしてください。','Enter the evaluation point as an integer, decimal, or fraction of no more than 24 characters.'],
['矢 c','Sagitta c'],
['直径 d','Diameter d'],
['朱の円弧の長さ s を求めます','Find the length s of the red arc'],
['直径 d の円、弦と矢 c、求める短い円弧 s','A circle of diameter d showing the chord, sagitta c, and required minor arc s.'],
['朱：選んだ解 ／ 青：与えた円','Red: selected solution / blue: given circles'],
['中心座標と半径に比例した接円図。極端に小さい円は見えにくくなります。','Tangent-circle diagram drawn to scale from the center coordinates and radii. Extremely small circles may be difficult to see.'],
['中心座標に基づく球の正投影。見かけの重なりは衝突を意味しません。','Orthographic projection of the spheres from their calculated centers. Apparent overlap does not indicate intersection.'],
['積分する関数','Integrand'],
['縦の尺度は、形が見やすいよう調整しています','The vertical scale is adjusted for legibility'],
['被積分関数の概形','Sketch of the integrand'],
['a と b は、中心から測る長さ','a and b are measured from the center'],
['半長軸aと半短軸bの楕円','Ellipse with semimajor axis a and semiminor axis b'],
['断面積 A(z)','Cross-sectional area A(z)'],
['z≥0 側の断面。面積の積分を2倍して体積へ','Cross-sections for z≥0; double the area integral to obtain the volume'],
['高さzによる二円柱の共通断面積の変化','Common cross-sectional area of the two cylinders as height z varies'],
['元の円','Original circle'],
['反転した図形','Inverted figure'],
['破線：反転円 ／ 左右は別々の尺度','Dashed: inverted circle / separate scales on left and right'],
['元の円と、その反転後の円または直線','Original circle and its image, which may be a circle or a line'],
['朱：出発する円 ／ すべて同じ尺度','Red: starting circle / all circles shown at the same scale'],
['中心がずれた二円の間をつなぐ円の連鎖','Chain of circles between two nonconcentric circles'],
['朱の破線：次に戻る位置。閉鎖していません','Red dashed circle: next return position; the chain does not close'],
['正多角形と外接円','Regular polygon and its circumcircle'],
['朱色：弦と円弧で囲まれた部分','Red: region bounded by the chord and arc'],
['円の弧と弦に挟まれた部分','Circular segment between an arc and its chord'],
['回転軸を含む断面の概形 ／ 横と縦は同じ尺度','Cross-section through the axis / same scale on both axes'],
['多項式を半径とする回転体の断面','Cross-section of the solid whose radius is given by the polynomial'],
['すべての円を同じ尺度で表示','All circles shown at the same scale'],
['大きい半円と内円に接しながら続く円の連鎖','Circle chain tangent to the large semicircle and an inner circle'],
['図は最初の20円 ／ 全100円は表に表示','Diagram: first 20 circles / table: all 100 circles'],
['四辺の順序を保った形 ／ 二本の対角線','Sides shown in their given order / both diagonals'],
['円に内接する四角形と対角線','Cyclic quadrilateral and its diagonals'],
['朱色：Aからの三辺 ／ 斜めからの正投影','Red: three edges from A / oblique orthographic projection'],
['六辺から配置した四面体の正投影','Orthographic projection of the tetrahedron reconstructed from its six edges'],
['朱色：最後に残る番号 ／ 上の1から時計回り','Red: final survivor / clockwise from 1 at the top'],
['円形に並ぶ番号と最後に残る番号','Circular arrangement and final surviving number'],
['近','Near'],
['遠','Far'],
['同じ地面・同じ目の高さ ／ 横と縦は同じ尺度','Same ground level and eye height / equal horizontal and vertical scales'],
['二地点から同じ目標の高さを見る測量図','Survey diagram sighting the same target from two stations'],
['整数の三辺 ／ 直角を挟む辺の比を反映','Integer sides / proportions of the two legs shown'],
['整数の三辺を持つ直角三角形','Right triangle with integer side lengths'],
['朱色：面積重心 ／ 数字：入力した頂点の順','Red: area centroid / numbers: input order of the vertices'],
['頂点の順に結んだ多角形と面積重心','Polygon joined in vertex order, with its area centroid'],
['球の中心を通る断面 ／ 朱色：立体の重心','Section through the sphere’s center / red: centroid of the solid'],
['二平面の間の球の断面と立体の重心','Sphere section between two planes, with the solid’s centroid'],
['回転軸を通る断面 ／ 朱色：回転軸','Section through the axis of revolution / red: axis'],
['円を回してできる環体の中心断面','Central section of the torus formed by revolving a circle'],
['三円どうしの外接と、それぞれの二辺への接触','The three circles are externally tangent to one another, and each touches two sides'],
['三角形の二辺と互いに接する三つの円','Three mutually tangent circles, each touching two sides of the triangle'],
['朱色：表の1番の解 ／ 他の解は表を参照','Red: solution 1 in the table / see the table for the other solutions'],
['三つの入力円と接円の第一解','Three input circles and the first tangent-circle solution'],
['最大','Maximum'],
['幅 w / (幅＋高さ)','Width w / (width + height)'],
['体積の変化 ／ 縦軸は最大体積を1として表示','Variation in volume / vertical axis normalized so the maximum is 1'],
['箱の幅を変えたときの体積と最大点','Volume as the box width changes, with the maximum marked'],
['朱色：底辺BCと三つの円に接する第4円','Red: fourth circle tangent to base BC and the other three circles'],
['三角形の中の安島の四円接触配置','Ajima’s four-circle tangency configuration inside a triangle'],
['合同な楕円を横向き・縦向きに配置','Congruent ellipses placed horizontally and vertically'],
['二等辺三角形に接する向きの異なる合同な二楕円','Two congruent ellipses in perpendicular orientations, tangent to an isosceles triangle'],
['中心は0 ／ 左から順に、指定した面積比で切断','Center at 0 / cuts placed from left to right at the specified area ratios'],
['円を指定した面積比へ分ける平行な切断線','Parallel cuts dividing a disk in the specified area ratios'],
['朱色：交点 ／ 円の中心・半径を基準に同じ尺度で表示','Red: intersections / equal scale based on the circle’s center and radius'],
['円と放物線の交点','Intersections of a circle and a parabola'],
['円の大きさは半径に比例。極端に大きさが違う場合、小さい円は見えにくくなります。','Circle sizes are proportional to their radii. A very small circle may be difficult to see when the scales differ greatly.'],
['青：内接値 ／ 朱：外接値。数学上の上下界を、小数で近似計算しています。','Blue: inscribed value / red: circumscribed value. The mathematical bounds are displayed as decimal approximations.'],
['青は既知の点、朱は補間多項式から計算した点。曲線を描いたものではありません。','Blue marks known points; red marks the point evaluated from the interpolating polynomial. No curve is implied.'],
['入力値の平方根と厳密に一致しています。','This is exactly the square root of the input.'],
['外挿','Extrapolation'],
['入力された数値に対し、分数計算で f(x)=0 を確認しました。答えはその厳密な値です。','Exact fractional arithmetic verifies f(x)=0 for the entered value, which is therefore reported exactly.'],
['浮動小数の分解能に達したため終了しました。','Stopped at floating-point resolution.'],
['反復上限に達しました。','Stopped at the iteration limit.'],
['指定した区間幅に達したため終了しました。','Stopped after reaching the requested interval width.'],
['指定幅に未到達','requested width not reached'],
['n の大きさにかかわらず、p + 2 段までの差分を使って計算します。','The calculation uses differences only through level p + 2, regardless of the size of n.'],
['図は中心座標に基づく正投影。見る向きを変えられます。見かけの重なりは衝突を意味しません。','The drawing is an orthographic projection based on the center coordinates. Rotate the view to inspect it; apparent overlap does not imply intersection.'],
['数学上の上下からの見積もりを、小数で計算しています。丸め誤差を含めた厳密な保証区間ではありません。増約値も保証値ではありません。','The mathematical lower and upper estimates are evaluated in decimal arithmetic. They are not a certified interval including rounding error, and the accelerated value is not certified either.'],
['小数は、根を含む厳密な区間の中点からの目安です。近い別々の根が同じ小数表示になることもあります。表の区間と重複度を確認してください。','Each decimal is a guide based on the midpoint of a certified root interval. Distinct nearby roots may display as the same decimal; consult the intervals and multiplicities in the table.'],
['長く表示した小数の全てが確定桁ではありません。答えに添えた上下区間と、その幅で精度を確認してください。','Not every displayed decimal place is certified. Judge the precision from the accompanying bounds and their width.'],
['半径が等しい場合は厳密計算、それ以外は区間による評価です。小数の桁数だけでなく、表示された区間幅で精度を確認してください。','Equal radii are handled exactly; otherwise the value is enclosed by an interval. Judge precision from the displayed interval width, not merely from the number of decimal places.'],
['上下の見積もりも小数近似です。丸め誤差を含む厳密な保証区間ではありません。特に細長い楕円では、表示桁数を精度の保証と受け取らないでください。','The displayed lower and upper estimates are themselves decimal approximations, not a certified interval including rounding error. For a highly eccentric ellipse in particular, do not treat the number of displayed digits as a precision guarantee.'],
['級数の係数が指定次数まで一致することを確認しています。元の関数への誤差や収束を保証するものではありません。','The series coefficients are verified through the requested degree. This does not guarantee convergence or an error bound for the original function.'],
['指定した桁で切り捨てた値です。四捨五入ではありません。上下の区間は入力した十進数そのものに対する保証です。','The value is truncated at the requested place, not rounded. The enclosing interval is certified for the decimal input exactly as entered.'],
['指定した桁で切り捨てた値と厳密な上下区間を示します。四捨五入とは区別してください。','The result is truncated at the requested place and accompanied by exact bounds; it is not rounded.'],
['答えは指定桁までの切り捨て値です。四捨五入ではありません。計算過程の上下界で桁を確認しています。','The result is truncated to the requested place, not rounded. Its digits are certified by the bounds established during the calculation.'],
['読み物を選ぶ','Choose an article'],
['計算の一覧を開く','Open the calculation index'],
['計算の表（左右にスクロールできます）','Calculation table (scroll horizontally)'],
['曲線の一部は表示精度を超えるため省略しました。交点の値は表で確認できます。','Part of the curve exceeds display precision and is omitted. See the table for the intersection values.'],
['61人以上の配置は、下の順番の表で確認できます。','For 61 or more people, consult the order table below.'],
['入力した三円 ／ 正の半径の接円なし','Input circles / no positive-radius tangent circle'],
['始','Start'],
['終','End'],
['朱色：計算する弧 ／ 角度は媒介変数','Red: arc being calculated / angle is the curve parameter'],
['楕円上の指定した弧','Selected arc of the ellipse'],
['図で扱える数値範囲を超えています。厳密な体積は答えと表を参照してください。','The values exceed the drawable range. See the answer and table for the exact volume.'],
['値が大きいため図を省略します。厳密な値は表を参照してください。','The values are too large to draw. See the table for the exact values.'],
];
