/* AI NOBORU — https://www.aiofonesown.com/ | 出典を示す配布用表示。参照史料・第三者の権利表示は各記載を参照。 */
import {frontierEngines} from './frontier.mjs';
import {renderFrontierGeometry} from './frontier-view.mjs';
import {discoveryEngines} from './discovery.mjs';
import {renderDiscoveryGeometry} from './discovery-view.mjs';
import {expansionEngines} from './expansion.mjs';
import {renderExpansionGeometry} from './expansion-view.mjs';
import {toolIndexMarkup} from './navigation.mjs';
import {masteryEngines} from './mastery.mjs';
import {renderMasteryGeometry} from './mastery-view.mjs';
import {catalog} from './catalog.mjs';
import {readingPages,renderReading} from './reading.mjs';
import * as math from './math.mjs';
import {advancedEngines} from './advanced.mjs';
import {renderAdvancedGeometry} from './advanced-view.mjs';
import {extraEngines} from './extra-math.mjs';
import {bindKids} from './kids.mjs';
const $=id=>document.getElementById(id);
const english=document.documentElement.lang==='en';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,d=12)=>Number.isFinite(n)?Number(n.toPrecision(d)).toLocaleString('en-US',{maximumSignificantDigits:d,useGrouping:false}):'表示範囲外';
const small=n=>Math.abs(n)<1e-5&&n!==0?Number(n).toExponential(4):fmt(n,10);
const table=(heads,rows)=>`<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
const svg=(body,label,cls='drawing')=>`<svg class="${cls}" viewBox="0 0 520 358" role="img" aria-label="${esc(label)}" xmlns="http://www.w3.org/2000/svg">${body}<g data-ainoboru-attribution="true"><rect x="0" y="330" width="520" height="28" fill="#183744"/><a href="https://www.aiofonesown.com/"><text x="260" y="349" text-anchor="middle" font-family="sans-serif" font-size="13" fill="white" style="fill:#fff;font-size:16px;font-family:sans-serif">AI NOBORU · www.aiofonesown.com</text></a></g></svg>`;
let active=catalog[0],lastResult=null,lastCopy='';
const saved={};
const defaults=c=>Object.fromEntries(c.fields.map(f=>[f.key,f.value]));
const values=()=>Object.fromEntries(active.fields.map(f=>[f.key,math.normal($('input-'+f.key).value)]));
const engines={...frontierEngines,...discoveryEngines,...expansionEngines,...extraEngines,...advancedEngines,...masteryEngines,sangaku:p=>math.contactCircles(p.a,p.b),enri:p=>math.circlePi(p.rounds),shosa:p=>math.interpolate(p.values,p.x0,p.h,p.x),kaiho:p=>math.squareRoot(p.value,p.precision),tengen:p=>math.polynomialRoot(p.coefficients,p.lower,p.upper,p.tolerance),hyakugo:p=>math.remainders(p.conditions),tawara:p=>math.powerSum(p.n,p.power)};
function field(f,v){const id='input-'+f.key;let control;if(f.kind==='textarea')control=`<textarea id="${id}" name="${f.key}" rows="3" spellcheck="false" ${f.hint?`aria-describedby="hint-${f.key}"`:''}>${esc(v)}</textarea>`;else if(f.kind==='select')control=`<select id="${id}" name="${f.key}">${(f.options.some(o=>String(o)===String(v))?f.options:[...f.options,v]).map(o=>`<option value="${esc(o)}" ${String(o)===String(v)?'selected':''}>${esc(o)}</option>`).join('')}</select>`;else control=`<input id="${id}" name="${f.key}" type="text" value="${esc(v)}" ${f.kind==='decimal'?'inputmode="decimal"':''} spellcheck="false" autocomplete="off" maxlength="1400" ${f.hint?`aria-describedby="hint-${f.key}"`:''}>`;return `<div class="field ${f.wide?'wide':''}"><label for="${id}">${esc(f.label)}</label>${control}${f.hint?`<p class="hint" id="hint-${f.key}">${esc(f.hint)}</p>`:''}</div>`;}
const further={tengen:[{id:'elimination',name:'上級へ：消去と行列式'},{id:'roots',name:'すべての実根を調べる'}],enri:[{id:'arc',name:'上級へ：建部の円弧級数'},{id:'pi',name:'円周率50桁を確定する'}],sangaku:[{id:'descartes',name:'上級へ：三円から二つの接円'}]};
const masteryFurther={tawara:[{id:'bernoulli',name:'極み：和を作る係数へ'}],arc:[{id:'ellipse',name:'極み：楕円の周長へ'}],pi:[{id:'ellipse',name:'極み：円から楕円へ'}],elimination:[{id:'replacement',name:'極意：一般の換式へ'}],hexlet:[{id:'inversion',name:'極意：反転の仕組みへ'},{id:'steiner',name:'極意：平面の円の連鎖へ'}]};
const expansionFurther={enri:[{id:'kakujutsu',name:'角術と正多角形へ'}],replacement:[{id:'polygcd',name:'共通因子を取り出す'}],roots:[{id:'discriminant',name:'重根と判別式へ'}],tengen:[{id:'translation',name:'方程式を転位する'}],ellipse:[{id:'ellipticarc',name:'一部分の弧長を求める'}],enritable:[{id:'revolution',name:'曲線を回して求積する'}],steiner:[{id:'pappus',name:'半円の内側の連鎖へ'}]};
const discoveryFurther={tetrahedron:[{id:"josephus",name:"深化へ：継子立てと算脱"}],sangaku:[{id:"malfatti",name:"三角形の中の三円へ"}],kakujutsu:[{id:"cyclotomic",name:"角を表す最小多項式へ"}],shosa:[{id:"hermite",name:"値と傾きの補間へ"}],series:[{id:"reversion",name:"逆級数を求める"}],polygcd:[{id:"squarefree",name:"重複度ごとに因子を分ける"}]};
const frontierFurther={cyclotomic:[{id:"boxmax",name:"探究へ：建部の極大体積"}],malfatti:[{id:"ajima4",name:"安島の四円配置へ"}],ellipse:[{id:"ellipsetriangle",name:"楕円の接触と最小高さへ"}],segment:[{id:"diskcuts",name:"面積から切断位置を求める"}],pythagorean:[{id:"heronpell",name:"整数面積の三角形へ"}],reversion:[{id:"implicitseries",name:"一般の方程式を級数にする"}]};
const toolPath=c=>{const links=[...(frontierFurther[c.id]||[]),...(discoveryFurther[c.id]||[]),...(expansionFurther[c.id]||[]),...(c.related||further[c.id]||[]),...(masteryFurther[c.id]||[])];return links.length?'<nav class="tool-path" aria-label="つながる術">'+links.map(l=>'<a href="#'+esc(l.id)+'">'+esc(l.name)+' →</a>').join('')+'</nav>':''};
function renderShell(c,p){active=c;const i=catalog.indexOf(c);renderNavigation(catalog,c.id,false);$('workspace').innerHTML=`<section class="workspace-heading"><p class="kicker">${esc(c.category)} / ${esc(c.name)}</p><div class="title-row"><h1>${esc(c.title)}</h1><span class="mode-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span></div><p class="intro">${esc(c.intro)}</p><details class="tool-provenance"><summary>史料と計算法の位置づけ</summary><p>${esc(c.history)}</p><p class="hint">史料を参考にした再構成と、現代数学による比較・補助を区別しています。具体的な出典は「参考資料」から読めます。</p></details></section><div class="workbench"><div><section class="input-card"><h2 class="section-label">数を置く <span>INPUT</span></h2><div class="examples" aria-label="入力例">${c.examples.map((e,i)=>`<button class="example" data-example="${i}" type="button">${esc(e[0])}</button>`).join('')}</div><form id="calculator" novalidate><div class="fields">${c.fields.map(f=>field(f,p[f.key])).join('')}</div><button class="calculate" type="submit"><span>計算する</span><span aria-hidden="true">→</span></button><p id="input-status" class="hint" role="status" hidden></p><div id="error" class="error" role="alert"></div></form></section><section id="answer" aria-live="polite" aria-atomic="true"></section></div><section id="visual" class="visual-panel" aria-label="計算の図表"></section></div><div class="formula-strip"><span>この術の鍵</span><span class="formula">${esc(c.formula)}</span></div>${toolPath(c)}<div class="notes-grid"><section class="insight"><h2>和算の着眼点</h2><p>${esc(c.insight)}</p></section><section><h2>成立条件と範囲</h2><p>${esc(c.limits)}</p></section></div><details id="steps"><summary>途中式を読む</summary><p class="method">${esc(c.method)}</p><div id="steps-content"></div></details><details class="sources"><summary>参考資料</summary><p>${esc(c.history)}</p><div class="source-links">${c.sources.map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener noreferrer">${esc(s[0])} ↗</a>`).join('')}${c.id==='sangaku'?'<a href="#history">和算の背景と、受け継ぐ研究 →</a>':''}</div></details>`;$('calculator').addEventListener('submit',e=>{e.preventDefault();calculate();});$('calculator').addEventListener('input',()=>{saved[c.id]=values();$('input-status').hidden=false;$('input-status').textContent='入力を変更しました。計算するボタンで結果を更新します。';if($('answer-badge'))$('answer-badge').textContent='前回の計算結果';});document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{const next={...defaults(c),...c.examples[Number(b.dataset.example)][1]};c.fields.forEach(f=>$('input-'+f.key).value=next[f.key]);calculate();}));}
function circleDrawing(o){const xmin=-o.a,xmax=o.distance+o.b,span=xmax-xmin,height=2*Math.max(o.a,o.b),scale=Math.min(425/span,220/height),ox=(520-span*scale)/2-xmin*scale,base=260;const cx=x=>ox+x*scale,cy=r=>base-r*scale;const circle=(x,r,color,fill,label)=>`<circle cx="${cx(x)}" cy="${cy(r)}" r="${r*scale}" fill="${fill}" stroke="${color}" stroke-width="2"/><line x1="${cx(x)}" y1="${cy(r)}" x2="${cx(x)}" y2="${base}" stroke="${color}" stroke-width="1" stroke-dasharray="3 4"/>${r*scale>23?`<text class="math-label" x="${cx(x)}" y="${cy(r)-9}" text-anchor="middle">${label}</text>`:''}`;return svg(`<defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#d7e1e5"/></pattern></defs><rect x="15" y="10" width="490" height="285" fill="url(#grid)"/><line x1="24" y1="${base}" x2="496" y2="${base}" stroke="#708891" stroke-width="1.4"/>${circle(0,o.a,'#244a5d','#dce7ec99','a')}${circle(o.distance,o.b,'#447d86','#dfedec99','b')}${circle(o.x,o.r,'#c24e38','#e58b6877','')}<circle cx="${cx(o.x)}" cy="${cy(o.r)}" r="2.5" fill="#c24e38"/><line x1="${cx(o.x)}" y1="${base+5}" x2="${cx(o.x)}" y2="290" stroke="#c24e38"/><text x="${cx(o.x)}" y="313" text-anchor="middle" style="fill:#a4402d">r = ${esc(fmt(o.r,9))}</text>`,`半径${o.a}と${o.b}の円と直線の隙間に、半径${fmt(o.r)}の円が接しています。`);}
function graph(points,{target=null,line=true,label='関数のグラフ'}={}){const pts=points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y));if(pts.length!==points.length||!pts.length||(target&&(!Number.isFinite(target.x)||!Number.isFinite(target.y))))return `<p class="empty-state">値が大きいため、グラフ表示を省略しています。<br>厳密な値は答えと表で確認できます。</p>`;const all=target&&Number.isFinite(target.x)&&Number.isFinite(target.y)?[...pts,target]:pts;let minX=Math.min(...all.map(p=>p.x)),maxX=Math.max(...all.map(p=>p.x)),minY=Math.min(0,...all.map(p=>p.y)),maxY=Math.max(0,...all.map(p=>p.y));if(!(maxX>minX))return `<p class="empty-state">小数では点の間隔を区別できないため、図示を省略しています。<br>答えと表を参照してください。</p>`;const dx=maxX-minX,dy=maxY-minY||1;minX-=dx*.08;maxX+=dx*.08;minY-=dy*.1;maxY+=dy*.12;if(!(maxX>minX)||!(maxY>minY))return `<p class="empty-state">小数では点の間隔を区別できないため、図示を省略しています。<br>答えと表を参照してください。</p>`;if(!Number.isFinite(maxY-minY)||!Number.isFinite(maxX-minX))return `<p class="empty-state">図示できる数値範囲を超えています。答えと表を参照してください。</p>`;const X=x=>55+(x-minX)/(maxX-minX)*430,Y=y=>280-(y-minY)/(maxY-minY)*250;let body='';for(let i=0;i<5;i++){const y=30+i*62.5;body+=`<line x1="55" y1="${y}" x2="485" y2="${y}" stroke="#dce5e8"/>`;}body+=`<line x1="55" y1="${Y(0)}" x2="485" y2="${Y(0)}" stroke="#9cb0b7"/><text x="48" y="${Y(0)+4}" text-anchor="end" style="font-size:11px">0</text>`;if(line)body+=`<polyline points="${pts.map(p=>`${X(p.x)},${Y(p.y)}`).join(' ')}" fill="none" stroke="#2c6375" stroke-width="2.5"/>`;else body+=pts.map(p=>`<circle cx="${X(p.x)}" cy="${Y(p.y)}" r="4" fill="#2c6375"/>`).join('');body+=`<text x="55" y="307" style="font-size:11px">${esc(small(minX+dx*.08))}</text><text x="485" y="307" text-anchor="end" style="font-size:11px">${esc(small(maxX-dx*.08))}</text><text x="14" y="30" style="font-size:11px">${esc(small(maxY-dy*.12))}</text><text x="14" y="280" style="font-size:11px">${esc(small(minY+dy*.1))}</text><text x="500" y="308" style="font-size:12px">x</text>`;if(target&&Number.isFinite(target.x)&&Number.isFinite(target.y))body+=`<line x1="${X(target.x)}" y1="${Y(target.y)}" x2="${X(target.x)}" y2="${Y(0)}" stroke="#c24e38" stroke-dasharray="3 4"/><circle cx="${X(target.x)}" cy="${Y(target.y)}" r="5.5" fill="#c24e38" stroke="#fff" stroke-width="2"/>`;return svg(body,label);}
function polygons(o){const n=Math.min(o.n,96),r=115,cx=260,cy=160;const pts=(radius,phase)=>Array.from({length:n},(_,i)=>`${cx+radius*Math.cos(2*Math.PI*i/n+phase)},${cy+radius*Math.sin(2*Math.PI*i/n+phase)}`).join(' ');return svg(`<circle cx="${cx}" cy="${cy}" r="${r}" fill="#fff" stroke="#91a8b2" stroke-width="1"/><polygon points="${pts(r/Math.cos(Math.PI/n),Math.PI/n)}" fill="none" stroke="#c24e38" stroke-width="1.5"/><polygon points="${pts(r,0)}" fill="#dce8ed44" stroke="#24667c" stroke-width="1.7"/><line x1="260" y1="160" x2="375" y2="160" stroke="#8da8b1" stroke-dasharray="3 4"/><circle cx="260" cy="160" r="2.5" fill="#183744"/><text x="315" y="149" text-anchor="middle" style="font-size:12px">半径 1</text><text x="260" y="310" text-anchor="middle" style="font-size:12px">${o.n>96?'図は96角形で表示 / 計算は'+o.n.toLocaleString('ja-JP')+'角形':o.n+'角形'}</text>`,`円と内外接${n}角形。計算には${o.n}角形を使用。`);}
const termTable=terms=>table(['次数 k','先頭差分 Δᵏ','二項係数 C','掛けた値'],terms.map(t=>[t.k,t.difference,t.binomial,t.contribution]));
function resultView(c,p,o){let value,detail,visual,steps,caption,visualTitle='図で見る',meta='';switch(c.id){case 'sangaku':value=fmt(o.r,14);detail=`a = ${fmt(o.a)}、b = ${fmt(o.b)} と同じ単位`;visual=circleDrawing(o)+`<div class="diagram-legend"><span><i class="legend-dot" style="background:#244a5d"></i>円 a</span><span><i class="legend-dot" style="background:#447d86"></i>円 b</span><span><i class="legend-dot" style="background:#c24e38"></i>求める円 r</span></div>`;caption='円の大きさは半径に比例。極端に大きさが違う場合、小さい円は見えにくくなります。';steps=`<ol class="steps-text"><li>大きい2円の接点間距離：2√ab = ${esc(fmt(o.distance))}</li><li>隙間で分ける：√ab = √ar + √br</li><li>√r で括る：√ab = √r (√a + √b)</li><li>r = (√ab / (√a + √b))² = ${esc(fmt(o.r,14))}</li><li>中心間距離と半径の和の最大差：${esc(small(o.residual))}（浮動小数での検算）</li></ol>`;meta='接触条件から計算';break;
case 'enri':value=`${fmt(o.lower,15)}\n< π <\n${fmt(o.upper,15)}`;detail=`${o.n.toLocaleString('ja-JP')}角形 / 範囲の幅 ${small(o.gap)}`;visual=polygons(o);caption='青：内接値 ／ 朱：外接値。数学上の上下界を、小数で近似計算しています。';steps=table(['辺の数','内接値','外接値','幅'],o.rows.map(r=>[r.n,fmt(r.lower,15),fmt(r.upper,15),small(r.gap)]));if(o.accelerated!==null){visual+=`<div class="fraction-callout"><p>増約による3項の外挿</p><strong>${esc(fmt(o.accelerated,15))}</strong><p>直前3つの内接値から計算。保証された上下界ではありません。</p></div>`;steps+=`<p class="method">3つの連続する内接値を a, b, c として、b + (b−a)(c−b) / ((b−a)−(c−b)) = ${esc(fmt(o.accelerated,15))}。この変換は現代では Aitken の Δ² 法としても知られます。</p>`;}else steps+='<p class="method">増約を比べるには、辺を倍にする回数を2以上にします。</p>';meta='小数15桁程度の表示';break;
case 'shosa':value=o.value;detail=`t = ${o.t} / ${o.degree<0?'零多項式':'補間多項式の次数 '+o.degree}`;visualTitle='既知の点と求めた点';visual=graph(o.points,{target:o.target,line:false,label:'青は既知の点、朱は補間多項式から計算した点。曲線を描いたものではありません。'});visual+=`<div class="diagram-legend"><span><i class="legend-dot" style="background:#2c6375"></i>既知の点</span><span><i class="legend-dot" style="background:#c24e38"></i>計算した点</span></div>`;caption='図は小数による表示。答えと差分表は分数まで厳密に計算しています。';steps=(o.extrapolation?'<p class="notice">求めた位置は既知の点の範囲外です。これは外挿であり、実際の数列や現象の続きを保証しません。</p>':'')+table(['差分の段','各段の値'],o.table.map((row,k)=>[`Δ${k}`,row.join('　,　')]))+termTable(o.terms);if(o.extrapolation)detail+=' / 外挿';meta='約分した有理数';break;
case 'kaiho':value=o.value;detail=o.exact?'入力値の平方根と厳密に一致しています。':`${o.value} ≤ √N < ${o.upper}`;visualTitle='一桁ずつ決める';visual=`<div class="sqrt-equation">√${esc(p.value)}<br><span style="color:var(--accent)">${o.exact?'= ':'≈ '}${esc(o.value)}</span></div><div class="visual-table">${table(['下ろす2桁','選ぶ桁 q','余り'],o.steps.slice(0,7).map(s=>[s.pair,s.digit,s.remainder]))}</div>`;caption=`最初の${Math.min(7,o.steps.length)}段を表示。全${o.steps.length}段は「途中式を読む」で確認できます。`;steps=table(['段','下ろす2桁','既決の桁 p','比較する数','次の桁 q','引く数','余り'],o.steps.map((s,i)=>[i+1,s.pair,s.previous,s.expanded,s.digit,s.subtraction,s.remainder]));meta=o.exact?'厳密値':'指定した桁で切り捨て';break;
case 'tengen':value=o.rootText;detail=`f(x) ≈ ${small(o.residual)} / ${o.rows.length}回の区間分割${['precision','limit'].includes(o.reason)?' / 指定幅に未到達':''}`;visualTitle='係数と関数の形';visual=`<div class="coefficient-strip">${o.coefficientText.map((a,i)=>`<div class="coefficient ${a<0?'negative':''}"><b>${esc(a)}</b><span>${o.coefficients.length-1-i===0?'定数':`x${['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸'][o.coefficients.length-1-i]}`}</span></div>`).join('')}</div>`+graph(o.points,{target:{x:o.root,y:0},label:'指定区間の多項式と求めた根の位置。グラフは81点の標本を直線で結んだもの。'});caption='係数は現代的転写。グラフは81点を結ぶ概形で、すべての根を示すものではありません。';steps=`<p class="method">最終区間：[${esc(o.lowerText)}, ${esc(o.upperText)}]。幅 ${esc(o.widthText)}。${o.reason==='exact-zero'||o.reason==='endpoint'?'入力された数値に対し、分数計算で f(x)=0 を確認しました。答えはその厳密な値です。':o.reason==='precision'?'浮動小数の分解能に達したため終了しました。':o.reason==='limit'?'反復上限に達しました。':'指定した区間幅に達したため終了しました。'}</p>`+table(['回','左端','右端','中点 x','f(x) の近似'],o.rows.map(r=>[r.iteration,r.lowerText,r.upperText,r.midText,small(r.value)]));meta=['exact-zero','endpoint'].includes(o.reason)?'二分法で確認した厳密な根':'二分法の最終中点（根の近似）';break;
case 'hyakugo':value=o.value;detail=`すべての整数解：${o.value} + ${o.period} × k（k は整数）`;visualTitle='条件を一つずつ重ねる';visual=`<div class="visual-table">${table(['割る数','余り','統合後の最小値','周期'],o.rows.map(r=>[r.modulus,r.remainder,r.solution,r.period]))}</div><div class="fraction-callout"><p>条件をすべて満たす周期</p><strong>${esc(o.period)}</strong><p>各条件の割る数の最小公倍数</p></div>`;caption='互いに素でない割る数も、余りの条件が両立すれば計算できます。';steps=table(['割る数','正規化した余り','ここまでの gcd','統合結果','周期'],o.rows.map(r=>[r.modulus,r.remainder,r.gcd,r.solution,r.period]))+`<p class="method">再代入：${o.rows.map(r=>`${o.value} mod ${r.modulus} = ${BigInt(o.value)%BigInt(r.modulus)}`).map(esc).join(' ／ ')}</p>`;meta='最小の非負整数';break;
case 'tawara':value=o.value;detail=`n = ${o.n}、p = ${o.power} / ${o.n==='0'?'空の和':`1${['⁰','¹','²','³','⁴','⁵','⁶','⁷','⁸','⁹'][o.power]||'^'+o.power} から n${o.power===1?'':`^${o.power}`} まで`}`;visualTitle='和の規則を取り出す';visual=`<div class="visual-table">${termTable(o.terms)}</div>`;caption='n の大きさにかかわらず、p + 2 段までの差分を使って計算します。';steps=table(['差分の段','各段の値'],o.table.map((row,k)=>[`Δ${k}`,row.join('　,　')]))+termTable(o.terms);meta='整数演算による厳密値';break;
default:value=o.value;detail=o.detail;meta=o.meta;visualTitle=c.name+'の計算';visual=(renderFrontierGeometry(o.geometry)||renderDiscoveryGeometry(o.geometry)||renderExpansionGeometry(o.geometry)||renderMasteryGeometry(o.geometry)||renderAdvancedGeometry(o.geometry))+table(o.heads,o.rows);steps='<ol class="steps-text">'+o.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>';caption=o.geometry?.dimension===3?'図は中心座標に基づく正投影。見る向きを変えられます。見かけの重なりは衝突を意味しません。':c.method;break;}
lastResult={mode:c.id,value,detail};lastCopy=english?`WASAN Mathematics Laboratory | ${c.name}\nInput: ${Object.entries(p).map(([k,v])=>`${k}=${v}`).join(', ')}\nResult: ${value}\n${detail}\n${meta}`:`和算 計算室｜${c.name}\n入力：${Object.entries(p).map(([k,v])=>`${k}=${v}`).join(', ')}\n結果：${value}\n${detail}\n${meta}`;lastCopy+='\nAI NOBORU — https://www.aiofonesown.com/';$('answer').innerHTML=`<div class="answer-card"><div class="answer-top"><span class="answer-label">${esc(c.resultLabel)}</span><span class="badge" id="answer-badge">${esc(c.badge)}</span></div><p class="answer-value ${String(value).length>25?'long':''}">${esc(value).replaceAll('\n','<br>')}</p><p class="answer-detail">${esc(detail)}</p>${resultPrecision(c,o)?`<p class="answer-precision"><strong>この数値の読み方</strong>${esc(resultPrecision(c,o))}</p>`:''}<p class="result-attribution" data-ainoboru-result-attribution><a href="https://www.aiofonesown.com/">AI NOBORU · www.aiofonesown.com</a></p><div class="answer-foot"><span class="exact-note">${esc(meta)}</span><button class="copy" id="copy-result" type="button">結果をコピー ⧉</button></div></div>`;$('visual').innerHTML=`<div class="visual-heading"><span>${esc(visualTitle)}</span><span>FIG. ${String(catalog.indexOf(c)+1).padStart(2,'0')}</span></div>${visual}<p class="visual-caption">${esc(caption)}</p>`;$('steps-content').innerHTML=steps;if(o.transfer){const target=catalog.find(c=>c.id===o.transfer.mode);if(target){const button=document.createElement('button');button.type='button';button.id='transfer-tool';button.className='transfer-tool';button.textContent='この式の実根を調べる →';button.addEventListener('click',()=>{saved[target.id]={...defaults(target),...o.transfer.input};location.hash='#'+target.id;});$('answer').append(button);}}const copyButton=$('copy-result'),copyAnswer=$('answer'),copyText=lastCopy;copyButton.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(copyText);if(copyButton.isConnected)copyButton.textContent='コピーしました';}catch{if(!copyButton.isConnected)return;copyButton.textContent='答えを選択してコピー';const selection=window.getSelection();if(!selection)return;const range=document.createRange();range.selectNodeContents(copyAnswer);selection.removeAllRanges();selection.addRange(range);}});}
function resultPrecision(c,o){
 if(c.id==='tengen'&&!['exact-zero','endpoint'].includes(o.reason))return `表示値は根を含む最終区間の中点です。区間 [${o.lowerText}, ${o.upperText}]、幅 ${o.widthText}。表示した全桁が根の確定桁ではありません。根の一意性も保証しません。${['precision','limit'].includes(o.reason)?'指定幅には到達していません。':''}`;
 const notes={
  enri:'数学上の上下からの見積もりを、小数で計算しています。丸め誤差を含めた厳密な保証区間ではありません。増約値も保証値ではありません。',
  roots:'小数は、根を含む厳密な区間の中点からの目安です。近い別々の根が同じ小数表示になることもあります。表の区間と重複度を確認してください。',
  ellipse:'長く表示した小数の全てが確定桁ではありません。答えに添えた上下区間と、その幅で精度を確認してください。',
  cylinders:'半径が等しい場合は厳密計算、それ以外は区間による評価です。小数の桁数だけでなく、表示された区間幅で精度を確認してください。',
  ellipticarc:'上下の見積もりも小数近似です。丸め誤差を含む厳密な保証区間ではありません。特に細長い楕円では、表示桁数を精度の保証と受け取らないでください。',
  pade:'級数の係数が指定次数まで一致することを確認しています。元の関数への誤差や収束を保証するものではありません。',
  kaiho:'指定した桁で切り捨てた値です。四捨五入ではありません。上下の区間は入力した十進数そのものに対する保証です。',
  kairitsu:'指定した桁で切り捨てた値と厳密な上下区間を示します。四捨五入とは区別してください。',
  pi:'答えは指定桁までの切り捨て値です。四捨五入ではありません。計算過程の上下界で桁を確認しています。'
 };
 return notes[c.id]||'';
}
function calculate(){const p=values();saved[active.id]=p;$('input-status').hidden=true;$('error').textContent='';try{const result=engines[active.id](p);resultView(active,p,result);if(english&&typeof window.__wasanLocalize==='function')lastResult={...lastResult,value:window.__wasanLocalize(lastResult.value),detail:window.__wasanLocalize(lastResult.detail)};return lastResult;}catch(e){lastResult=null;$('error').textContent=e.message;$('answer').innerHTML='';$('visual').innerHTML='<p class="empty-state">入力の条件を確認してください。<br>修正すると、ここに図表が表示されます。</p>';$('steps-content').innerHTML='<p class="method">有効な入力で計算すると途中式を表示します。</p>';return {error:english&&typeof window.__wasanLocalize==='function'?window.__wasanLocalize(e.message):e.message};}}
function renderNavigation(items,id,reading){
  document.querySelector('.skip').textContent=reading?'本文へ移動':'計算へ移動';
  $('navigation').setAttribute('aria-label',reading?'和算の読み物':'計算の種類');
  document.getElementById('navigation-pages')?.remove();
  let range='';
  if(reading){$('navigation').innerHTML=items.map(v=>`<a class="nav-item" href="#${v.id}" ${v.id===id?'aria-current="page"':''}><span class="nav-num" aria-hidden="true">${v.no}</span><span><span class="nav-label">${v.name}</span><span class="nav-sub">${v.sub}</span></span></a>`).join('');}
  else{
    const markup=toolIndexMarkup(items,id);range=markup.range;$('navigation').innerHTML=markup.nav;
    const pages=document.createElement('nav');pages.id='navigation-pages';pages.setAttribute('aria-label','計算の一覧ページ');pages.innerHTML=markup.pages;
    $('navigation').before(pages);
    pages.querySelector('[aria-current]')?.addEventListener('click',e=>e.preventDefault());
  }
  $('navigation').dataset.total=String(items.length);
  const nav=$('navigation'),selected=nav.querySelector('[aria-current="page"]');
  if(selected&&nav.clientWidth>0&&nav.scrollWidth>nav.clientWidth){
    const item=selected.getBoundingClientRect(),frame=nav.getBoundingClientRect();
    nav.scrollLeft=Math.max(0,Math.min(nav.scrollWidth-nav.clientWidth,nav.scrollLeft+item.left-frame.left-(nav.clientWidth-item.width)/2));
  }
  document.querySelector('.eyebrow').innerHTML=reading?'和算を知る <span>読み物</span>':`術を選ぶ <span>${range}</span>`;
  document.querySelector('.sidebar-note').innerHTML=reading?'<span class="tiny-rule"></span><p>問いは、受け継がれる。</p><span>歴史を読み、数を動かし、また考える。</span>':'<span class="tiny-rule"></span><p>答えから、考え方へ。</p><span>各計算に途中式・成立条件・出典を添えています。</span>';
  for(const [key,current] of [['calculator-link',!reading],['reading-link',reading]]){if(current)$(key).setAttribute('aria-current','page');else $(key).removeAttribute('aria-current');}
}
function switchMode(id,params=null){
  if($('calculator'))saved[active.id]=values();
  const page=readingPages.find(p=>p.id===id);
  if(page){renderNavigation(readingPages,page.id,true);$('workspace').innerHTML=renderReading(page);bindKids($('workspace'));document.title=page.name+'｜和算 WASAN';return;}
  const c=catalog.find(c=>c.id===id)||catalog[0],p=params||saved[c.id]||defaults(c);renderShell(c,p);calculate();document.title=c.name+'｜和算 WASAN 計算室';
}
window.addEventListener('hashchange',()=>{if(location.hash==='#workspace'){$('workspace').focus();return;}switchMode(location.hash.slice(1));window.scrollTo(0,0);$('workspace').focus({preventScroll:true});});
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();$('workspace').focus();});
// Preserve valid reading deep links as well as calculator links on first load.
if(![...catalog,...readingPages].some(c=>'#'+c.id===location.hash))history.replaceState(null,'','#sangaku');
switchMode(location.hash.slice(1));
$('help-button').addEventListener('click',()=>$('help-dialog').showModal());$('close-help').addEventListener('click',()=>$('help-dialog').close());$('help-dialog').addEventListener('click',e=>{if(e.target===$('help-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
const context=document.modelContext;
if(context?.registerTool){const lifecycle=new AbortController();const tool={name:'calculate_wasan',title:'和算の計算を実行',description:'指定した和算モードで計算し、入力・答え・図表を画面に反映する。各モードの必須キー: '+catalog.map(c=>c.id+'('+c.fields.map(f=>f.key).join(',')+')').join(', ')+'。input内の値はすべて文字列。',inputSchema:{type:'object',properties:{mode:{type:'string',enum:catalog.map(c=>c.id)},input:{type:'object',additionalProperties:{type:'string'}}},required:['mode','input'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(arg){if(!arg||typeof arg!=='object'||Object.keys(arg).some(k=>!['mode','input'].includes(k)))throw new Error('mode と input を指定してください。');const c=catalog.find(c=>c.id===arg.mode);if(!c||!arg.input||typeof arg.input!=='object'||Array.isArray(arg.input))throw new Error('有効なモードと入力オブジェクトが必要です。');const keys=c.fields.map(f=>f.key);if(Object.keys(arg.input).some(k=>!keys.includes(k))||keys.some(k=>typeof arg.input[k]!=='string'))throw new Error(`必須の文字列キー：${keys.join(', ')}`);const p=Object.fromEntries(keys.map(k=>[k,math.normal(arg.input[k])]));engines[c.id](p);history.replaceState(null,'','#'+c.id);switchMode(c.id,p);return {...lastResult};}};try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
