/* AI NOBORu — https://www.aiofonesown.com/ | 出典を示す配布用表示。参照史料・第三者の権利表示は各記載を参照。 */
import {frontierCatalog} from './frontier-catalog.mjs';
import {discoveryCatalog} from './discovery-catalog.mjs';
import {expansionCatalog} from './expansion-catalog.mjs';
import {masteryCatalog} from './mastery-catalog.mjs';
import {advancedCatalog} from './advanced-catalog.mjs';
import {extraCatalog} from './extra-catalog.mjs';
export const catalog=[
 {id:'sangaku',no:'一',name:'算額の接円',sub:'円と円の隙間を解く',category:'図形と接触',title:'接する円を求める',intro:'同じ直線に接し、互いに外接する2つの円。その間の隙間に、ぴったり収まる円を求めます。',badge:'小数の近似値',fields:[{key:'a',label:'左の円の半径 a',value:'9',kind:'decimal',hint:'0.000001〜1,000,000'},{key:'b',label:'右の円の半径 b',value:'4',kind:'decimal',hint:'a と同じ単位で入力'}],examples:[['9 と 4',{a:'9',b:'4'}],['同じ大きさ',{a:'5',b:'5'}],['大小の円',{a:'12',b:'3'}]],resultLabel:'隙間の円の半径 r',formula:'1 / √r = 1 / √a + 1 / √b',insight:'円の半径のままでは複雑な関係が、逆平方根を使うと足し算になります。図形に合った量を選ぶ、和算の接円問題で役立つ見方です。',method:'直線への接点間の距離は、2つの円の半径を a, b とすると 2√ab。大きな区間を小さな2区間に分け、2√ab = 2√ar + 2√br を解きます。',limits:'2つの円は同じ直線の同じ側にあり、互いに外接していることが条件です。求めるのは両円と直線に囲まれた有限の隙間の円です。入力と結果の単位は共通。',history:'算額に多い接円問題を、国立国会図書館が紹介する接点間距離の関係から構成した教材です。特定の算額をそのまま翻刻したものではありません。',sources:[['国立国会図書館｜算額・容術の問題','https://www.ndl.go.jp/math/s1/question3.html'],['国立国会図書館｜接円問題の解説','https://www.ndl.go.jp/math/s1/answer3.html']]},
 {id:'enri',no:'二',name:'円理と増約',sub:'多角形から円周率へ',category:'近似と収束',title:'円を、数で挟む',intro:'正六角形から辺を倍にして円へ近づけます。内接・外接の2つの値と、3項から収束を速める増約の考え方を比べます。',badge:'小数の近似値',fields:[{key:'rounds',label:'辺を倍にする回数',value:'7',kind:'select',options:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],hint:'6 × 2ⁿ 角形まで計算'}],examples:[['まずは六角形',{rounds:'0'}],['768角形',{rounds:'7'}],['より細かく',{rounds:'12'}]],resultLabel:'円周率 π の近似範囲',formula:'内接多角形の半周 < π < 外接多角形の半周',insight:'円そのものを直接求めず、計算できる多角形を細かくします。さらに値の変わり方から極限を見積もる「増約」という発想にも触れられます。',method:'半径1、s = sin(π/n) とすると、内接値は ns、外接値は ns/√(1−s²)。倍増時は s ← s/√(2(1+√(1−s²)))。差の小さい数同士を引く計算を避けています。',limits:'数学上は上下から挟みますが、表示値は約15〜16桁の浮動小数計算です。機械計算として厳密な区間保証はありません。増約値も誤差の保証値ではなく、上下界の外へ出る場合があります。',history:'円理のうち多角形による近似を現代記号で再構成しています。内外接の併用を関孝和個人の方法とはしていません。3項変換は関の増約術との関係を研究論文で確認できます。',sources:[['京都大学RIMS｜関孝和の円周率計算の研究','https://www.kurims.kyoto-u.ac.jp/~kyodo/kokyuroku/contents/pdf/1787-07.pdf']]},
 {id:'shosa',no:'三',name:'招差法',sub:'差分から未知の値へ',category:'数表と補間',title:'数の差から、続きを求める',intro:'等間隔に並ぶ値の差を取り、差の差を取り……。その表から、点をすべて通る多項式の値を計算します。',badge:'分数まで厳密',fields:[{key:'values',label:'既知の値 y₀, y₁, …',value:'0, 1, 4, 9, 16',kind:'text',wide:true,hint:'2〜12個。カンマ区切り。分数も使えます'},{key:'x0',label:'最初の位置 x₀',value:'0',kind:'text'},{key:'h',label:'刻み幅 h',value:'1',kind:'text'},{key:'x',label:'求めたい位置 x',value:'5',kind:'text',wide:true,hint:'例：5、0.5、1/2'}],examples:[['平方数の続き',{values:'0, 1, 4, 9, 16',x0:'0',h:'1',x:'5'}],['点のあいだ',{values:'0, 1, 4, 9',x0:'0',h:'1',x:'3/2'}],['立方数',{values:'1, 8, 27, 64',x0:'1',h:'1',x:'5'}]],resultLabel:'補間多項式の値 P(x)',formula:'P(x) = Σ C(t, k) Δᵏy₀　　t = (x − x₀) / h',insight:'値ではなく、変化の規則を読む計算です。差分が一定になると、その手前の数列を低い次数の多項式で表せます。',method:'差分表の各段の先頭に、一般化二項係数 C(t,k) を掛けて足します。整数・小数・分数は内部で有理数として扱い、分数の答えを保ちます。',limits:'n個の点を通る次数 n−1 以下の多項式を選ぶ方法です。未知の現象や数列の真の規則を保証しません。観測点の外の外挿、誤差を含む実測値、高次補間には注意してください。h は0以外。',history:'招差法は中国の暦算に由来する差分補間で、和算でも発展しました。この画面の前進差分・二項係数は現代的な表示です。',sources:[['大阪工業大学｜関孝和『授時発明』の解読研究','https://www.oit.ac.jp/labs/is/system/shinkai/Papers/202607_SekiJujiHatumei.pdf']]},
 {id:'kaiho',no:'四',name:'開方術',sub:'平方根を一桁ずつ',category:'桁と根',title:'平方根を、桁から組み立てる',intro:'数を2桁ずつ下ろし、次の一桁を決めます。小数点以下60桁まで、切り捨て値とそれを囲む区間を整数計算で求めます。',badge:'桁と区間を厳密計算',fields:[{key:'value',label:'平方根を求める数 N',value:'2',kind:'text',wide:true,hint:'0以上の整数・小数。指数表記を除く160文字以内'},{key:'precision',label:'小数点以下の桁数',value:'20',kind:'select',options:[0,2,5,10,12,20,30,40,50,60]}],examples:[['√2',{value:'2',precision:'20'}],['√12345',{value:'12345',precision:'10'}],['ぴったり開く数',{value:'15241578750190521',precision:'0'}]],resultLabel:'平方根 √N',formula:'(20p + q)q ≤ 次に下ろした数　　q ∈ {0, …, 9}',insight:'一度に根を当てず、すでに決めた桁を使って次の一桁を選びます。「平方したら元の数を超えない」という条件が、最後まで計算の軸です。',method:'既決の整数桁列を p、次の桁を q とします。余りに次の2桁を付け、(20p+q)q がそれを超えない最大の q を選びます。比較も余りも整数計算です。',limits:'答えは指定桁で切り捨てます。四捨五入ではありません。非負の実数の平方根が対象で、負数・複素数は扱いません。厳密区間は入力した十進数そのものに対する区間です。',history:'和算の桁別求根を理解するための開平筆算です。同様の方法は日本以外にもあり、和算だけの発明とはしていません。',sources:[['国立国会図書館｜和算における数値計算・開方','https://www.ndl.go.jp/math/s1/c3.html']]},
 {id:'tengen',no:'五',name:'天元術の入口',sub:'係数を並べて根を探す',category:'方程式',title:'未知数を置き、式を解く',intro:'最高次から係数を並べて一未知数の多項式を表します。指定した区間で、現代の二分法を補助に使って実数解を1つ探します。',badge:'現代の求根補助',fields:[{key:'coefficients',label:'係数（最高次 → 定数項）',value:'1, 0, -2',kind:'text',wide:true,hint:'例：x² − 2 = 0 は 1, 0, -2。1〜8次、各係数 ±10⁶以内'},{key:'lower',label:'区間の左端',value:'1',kind:'decimal'},{key:'upper',label:'区間の右端',value:'2',kind:'decimal'},{key:'tolerance',label:'区間の許容幅',value:'0.0000000001',kind:'select',wide:true,options:['0.0001','0.000001','0.00000001','0.0000000001','0.000000000001']}],examples:[['x² − 2',{coefficients:'1, 0, -2',lower:'1',upper:'2',tolerance:'0.0000000001'}],['x³ − x − 1',{coefficients:'1, 0, -1, -1',lower:'1',upper:'2',tolerance:'0.0000000001'}],['五次式',{coefficients:'1, 0, 0, 0, -1, -1',lower:'1',upper:'2',tolerance:'0.0000000001'}]],resultLabel:'指定した区間内の実数解 x',formula:'f(a) と f(b) の符号が異なる区間を、半分ずつにする',insight:'一つの未知数を基準に、式を係数の並びとして扱います。係数の構造を保ったまま計算する見方が、天元術を読む入口になります。',method:'係数は現代的な横並び表示です。求根には二分法を使用し、各回の中点と f(x) を残します。和算の天元術・開方術そのものを忠実再現した求根器ではありません。',limits:'両端の符号が異なる区間が必要です（端点が根の場合を除く）。全実根や根の一意性は保証しません。重根や同符号の区間の根は見逃す場合があります。複素根・記号的な根号解は対象外。符号とゼロは分数で厳密に判定し、解は小数で近似表示します。',history:'天元術は中国から伝わった一未知数の方程式の方法です。算木による係数表示を現代的に転写し、数値求根は別の補助機能として分けています。',sources:[['国立国会図書館｜天元術','https://www.ndl.go.jp/math/s1/1.html'],['国立国会図書館｜関孝和と傍書法','https://www.ndl.go.jp/math/s1/2.html']]},
 {id:'hyakugo',no:'六',name:'百五減算',sub:'余りから元の数へ',category:'整数と合同',title:'余りを合わせ、数を復元する',intro:'3で割ると2余り、5で割ると3余り、7で割ると2余る。こうした条件から、最小の非負整数と繰り返す周期を求めます。',badge:'大きな整数も厳密',fields:[{key:'conditions',label:'割る数, 余り（1行に1条件）',value:'3, 2\n5, 3\n7, 2',kind:'textarea',wide:true,hint:'1〜10行。割る数は2以上、各整数80桁以内'}],examples:[['百五減算',{conditions:'3, 2\n5, 3\n7, 2'}],['互いに素でなくても',{conditions:'4, 2\n6, 4'}],['矛盾する条件',{conditions:'4, 1\n6, 2'}]],resultLabel:'条件を満たす最小の非負整数',formula:'x ≡ r₁ (mod m₁),　x ≡ r₂ (mod m₂), …',insight:'元の数を一つずつ試さず、余りの条件を重ねます。答えは一つの数だけでなく、一定の周期で繰り返す数の族になります。',method:'3・5・7の場合は 70r₃ + 21r₅ + 15r₇ から105の倍数を引けます。一般入力では最大公約数と拡張ユークリッド法を使い、条件を1行ずつ統合します。',limits:'互いに素でない割る数も扱えますが、条件が矛盾すると解はありません。余りは0以上かつ割る数未満に正規化します。すべての整数解は x₀ + 周期 × k（kは整数）です。',history:'中国の『孫子算経』に由来する問題が和算でも扱われました。百五減算は3・5・7に対応する呼び名です。任意の割る数への一般化は現代的な拡張機能です。',sources:[['国立国会図書館｜百五減算','https://www.ndl.go.jp/math/s1/c2.html'],['国立国会図書館｜合同式の一般化','https://www.ndl.go.jp/math/s1/c2_2.html']]},
 {id:'tawara',no:'七',name:'俵杉算と累乗和',sub:'積み重なりをまとめる',category:'和と差分',title:'積み重ねた数を、一度に求める',intro:'1 + 2 + … + n という俵の積み重なりから、平方・立方・12乗までの和へ。大きな n でも、1つずつ足さずに厳密に計算します。',badge:'整数を厳密計算',fields:[{key:'n',label:'最後の数 n',value:'100',kind:'text',hint:'0以上、80桁以内の整数'},{key:'power',label:'各項の累乗 p',value:'1',kind:'select',options:[0,1,2,3,4,5,6,7,8,9,10,11,12]}],examples:[['10段の俵',{n:'10',power:'1'}],['平方の和',{n:'100',power:'2'}],['1兆項の和',{n:'1000000000000',power:'1'}]],resultLabel:'1ᵖ + 2ᵖ + … + nᵖ',formula:'S(n) = Σ ΔᵏS(0) · C(n, k)',insight:'単純に足していく代わりに、積み重なり全体の規則を式にします。和そのものの差分表を作ると、大きな項数にも同じ式を使えます。',method:'S(0)=0 から p+2 個の累積和を作り、その前進差分を求めます。S(n) は次数 p+1 の多項式なので、差分と二項係数の有限和で厳密に求まります。',limits:'n は0以上の整数、p は0〜12の整数です。p=0 は1を n 個足して n、n=0 は空の和で0とします。12乗までの一般化と使用する差分算法は教材の拡張です。',history:'俵杉算の三角形に積んだ俵の数を入口とし、和算でも扱われた累乗和につなげます。すべての累乗和を「俵杉算」と呼ぶものではありません。',sources:[['国立国会図書館｜垜術・累乗和','https://www.ndl.go.jp/math/s1/question2.html']]},
 ...extraCatalog, ...advancedCatalog,...masteryCatalog,...expansionCatalog,...discoveryCatalog,...frontierCatalog
];
