/* AI NOBORU — https://www.aiofonesown.com/ | 出典を示す配布用表示。参照史料・第三者の権利表示は各記載を参照。 */
const field=(key,label,value,hint='',wide=false)=>({key,label,value,hint,wide,kind:'text'});
const poly=(key,label,value)=>field(key,label,value,'最高次→定数項。12次以下、各数24文字・絶対値100万以下。小数・分数可',true);
const length=(key,label,value)=>field(key,label,value,'0.001〜1,000,000。小数・分数可');
const link=(id,name)=>({id,name});
const ndl=['国立国会図書館｜和算の展開','https://www.ndl.go.jp/math/s2/3.html'];
const seki=['国立国会図書館｜関孝和','https://www.ndl.go.jp/math/s1/2.html'];
const horner=['国立国会図書館｜組立除法と方程式の転位','https://www.ndl.go.jp/math/s1/c3.html'];
const taylor=['国立国会図書館｜係数比較と級数','https://www.ndl.go.jp/math/s1/c3_3.html'];
const res=['後藤・小松｜和算の換式と終結式','https://www.kurims.kyoto-u.ac.jp/~kyodo/kokyuroku/contents/pdf/1392-11.pdf'];
const mathworld=(label,page)=>['Wolfram MathWorld｜'+label,'https://mathworld.wolfram.com/'+page+'.html'];
const exact='分数まで厳密',approx='小数の近似値';
export const expansionCatalog=[
 {id:'kakujutsu',no:'二十九',name:'角術と正多角形',sub:'角を多項式へ',category:'探究 / 角術',title:'正多角形の角を、係数の規則で表す',intro:'3角形から60角形まで、一辺・面積・内接円を求めます。角の関係を表す多項式も、整数係数で組み立てます。',fields:[field('n','辺の数 n','7','3〜60の整数'),length('radius','外接円の半径 R','2')],examples:[['正七角形',{n:'7',radius:'2'}],['正二十角形',{n:'20',radius:'1'}],['正六角形',{n:'6',radius:'2'}]],resultLabel:'正多角形の一辺',badge:'係数と図形をつなぐ',formula:'C₀=2、C₁=t、Cₖ=tCₖ₋₁−Cₖ₋₂　／　Cₙ(t)=2',insight:'角を直接追う代わりに、角を表す数が満たす方程式を組み立てます。',method:'t=2cos(2π/n)。多項式は整数で生成し、辺・面積は三角関数で近似します。',limits:'nは3〜60。多項式は複数の角の候補を含み、求める角は2π/nです。図は入力した辺の数で描きます。',history:'関の正多角形研究を入口に、現代の角の漸化式で計算します。この漸化式を、失われた角術の定乗生成法そのものとするものではありません。',sources:[seki],related:[link('enri','円理と増約に戻る'),link('linear','次へ：多元の連立方程式')]},
 {id:'linear',no:'三十',name:'多元の連立方程式',sub:'未知数をまとめて解く',category:'探究 / 消去',title:'未知数を順に消し、解の全体を求める',intro:'2〜6個の未知数を含む一次式を解きます。解が一つの場合も、自由に動く変数が残る場合も、矛盾する場合も判定します。',fields:[{...field('matrix','係数と右辺（1行に1つの式）','1, 1, 1, 6\n2, -1, 1, 3\n1, 2, -1, 2','各行：x₁, x₂, …の係数、最後に右辺。2〜6行。各数24文字・絶対値100万以下',true),kind:'textarea'}],examples:[['三つの未知数',{}],['自由変数が残る',{matrix:'1, 1, 2\n2, 2, 4'}],['解がない',{matrix:'1, 1, 2\n2, 2, 5'}]],resultLabel:'連立方程式の解',badge:exact,formula:'係数のある行を選び、その未知数を他の行から消去する',insight:'式を一つずつ解くのではなく、係数の表を変形して関係をそろえます。',method:'現代の行基本変形を有理数で実行。特解と自由変数の方向を元の式へ再代入します。',limits:'未知数・式の数はそれぞれ2〜6。非線形の項や不等式は対象外。解が無数にあるときは途中式に全体の表し方を示します。',history:'和算では複数未知数を含む問題の消去が発展しました。この道具はその先を試す現代の線形代数による補助で、傍書法の記法を復刻したものではありません。',sources:[ndl,seki],related:[link('elimination','消去と行列式'),link('polygcd','次へ：多項式の共通因子')]},
 {id:'polygcd',no:'三十一',name:'多項式の共通因子',sub:'式に共通する因子',category:'探究 / 代数',title:'二つの多項式に共通する因子を取り出す',intro:'式を割り、余りを取り、また割る。その繰り返しから共通因子を求め、元の二式が確かに割り切れることを検算します。',fields:[poly('f','多項式 f の係数','1, 0, -1'),poly('g','多項式 g の係数','1, -2, 1')],examples:[['共通する一次式',{}],['重なる高次因子',{f:'1,1,-5,-1,8,-4',g:'5,4,-15,-2,8'}],['共通因子なし',{f:'1,0,1',g:'1,0,-1'}]],resultLabel:'最高次係数を1にした共通因子',badge:exact,formula:'gcd(f,g) = gcd(g, f を g で割った余り)',insight:'式の見た目では分からない共通構造を、次数を下げながら探します。',method:'分母を払った整数係数の擬除法を使用し、定数倍を除きながら共通因子を求めます。大きな余式は表では概要を表示します。',limits:'両方とも零多項式にはできません。最大12次。共通因子の最高次係数を1にそろえます。',history:'消去や重根を理解するための現代的な補助道具です。関の換式をそのまま互除法と同一視するものではありません。',sources:[res],related:[link('replacement','換式による一般消去'),link('discriminant','次へ：重根と判別式')]},
 {id:'discriminant',no:'三十二',name:'重根と判別式',sub:'根の重なりを調べる',category:'探究 / 代数',title:'方程式の根が重なるかを調べる',intro:'8次までの多項式から判別式を求めます。元の式とその導関数の共通因子も調べ、丸め誤差によらず重根を判定します。',fields:[{...poly('coefficients','多項式の係数','1, 0, -10, 0, 9'),hint:'最高次→定数項。1〜8次。各数24文字・絶対値100万以下'}],examples:[['四次式の判別式',{}],['重根がある',{coefficients:'1,-2,1'}],['三次式',{coefficients:'1,0,0,-2'}]],resultLabel:'現代の符号規約による判別式 D',badge:exact,formula:'D = (−1)^(n(n−1)/2) Res(f,f′) / aₙ',insight:'根を一つずつ求める前に、根が重なるという式の性質を判定できます。',method:'シルベスター行列式と、多項式の共通因子を有理数で計算します。',limits:'1〜8次。重根には複素数の重根も含みます。一般の高次式では、判別式の符号だけで実根数は決まりません。',history:'関の開方飜変之法に関する研究では、fとf′の共通根の条件が論じられます。この画面では現代の判別式の符号規約を採用しています。',sources:[res],related:[link('roots','実根の個数と重複度を調べる'),link('newtonsums','次へ：根の累乗和')]},
 {id:'newtonsums',no:'三十三',name:'根の累乗和',sub:'根を解かず和を知る',category:'探究 / 対称式',title:'方程式を解かず、根の累乗和を求める',intro:'すべての根の二乗和、三乗和、さらに30乗和まで。根を個別に表示できなくても、係数から和を分数で求められます。',fields:[poly('coefficients','方程式の係数','1, -6, 11, -6'),field('order','最後の累乗 k','8','1〜30の整数')],examples:[['三つの根の和',{}],['複素根も含む',{coefficients:'1,0,1',order:'8'}],['重根も数える',{coefficients:'1,-3,3,-1',order:'12'}]],resultLabel:'重複を含むすべての根の累乗和',badge:exact,formula:'Sₖ + a₁Sₖ₋₁ + … + aₖ₋₁S₁ + k aₖ = 0　（k≤n）',insight:'求めたい量が対称式なら、個々の根を求める手間を省けます。',method:'最高次係数を1にそろえ、現代のNewtonの恒等式を分数で順に計算します。',limits:'1〜12次、累乗1〜30。複素根を含み、重根も重複して数えます。整数1からNまでの累乗和とは異なります。',history:'和算の係数操作・消去を深く使うために添えた現代的な対称式の計算です。この一般公式を和算家個人の算法として帰属させてはいません。',sources:[res],related:[link('bernoulli','整数の累乗和と比べる'),link('nthroot','次へ：高次の開方')]},
 {id:'nthroot',no:'三十四',name:'高次の開方',sub:'二十乗根を区間で',category:'探究 / 開方',title:'高い累乗の逆を、厳密な区間で求める',intro:'2乗根から20乗根まで、小数40桁の区間で求めます。分数や負の奇数乗根にも対応し、端の値を累乗して確かめます。',fields:[field('value','開く数 N','2','80文字以内の整数・小数・分数',true),field('degree','開く次数 k','7','2〜20の整数'),field('precision','小数点以下の桁数','20','0〜40の整数')],examples:[['2の七乗根',{}],['負の五乗根',{value:'-32',degree:'5',precision:'10'}],['分数の四乗根',{value:'1/16',degree:'4',precision:'12'}]],resultLabel:'実数の k 乗根',badge:'厳密区間',formula:'Lᵏ ≤ N·10^(kp) < (L+1)ᵏ　（N≥0）',insight:'桁を決めるとは、累乗したときに越えるか越えないかを確かめることです。',method:'整数の二分探索と累乗の交差積比較を使用。歴史的な算木の桁別配置とは別の実装です。',limits:'偶数乗根はN≥0で非負の根を返します。負の数は奇数乗根に限ります。入力は80文字、小数は40桁まで。',history:'平方根・立方根から高次の開方へ進む補助道具です。和算や東アジアの開方を手がかりに、現代の整数比較で一般化しています。',sources:[horner],related:[link('kairitsu','開立術に戻る'),link('translation','次へ：方程式の転位')]},
 {id:'translation',no:'三十五',name:'方程式の転位',sub:'根の近くへ移す',category:'探究 / 開方と係数',title:'未知数の位置を変え、式を書き換える',intro:'x=u+h と置いたときの係数を、12次まで分数で展開します。根の近くへ原点を移す、開方の大切な操作を試せます。',fields:[poly('coefficients','元の多項式の係数','1, 2, 0, -3, 5'),field('shift','移す量 h','1/2','24文字・絶対値100万以下')],examples:[['半分だけ移す',{}],['根の近くへ',{coefficients:'1,0,-2',shift:'1.4'}],['大きな位を取り出す',{coefficients:'2,-473,-234,-711',shift:'200'}]],resultLabel:'f(u+h) の多項式',badge:exact,formula:'f(u+h) = Σ bₖuᵏ',insight:'大きな根をそのまま追う代わりに、分かっている部分を引いて小さな補正量を探します。',method:'Horner型の係数演算で展開し、逆向きの転位を全係数で検算します。',limits:'12次以下。定数式も入力可能。ここでは係数を移す操作までで、移した式の根を自動探索するものではありません。',history:'国立国会図書館が紹介する天元術・組立除法では、根を少しずつ近似するための係数の転位が説明されています。ここでは現代記号で操作を取り出します。',sources:[horner,taylor],related:[link('tengen','移した式から根を探す'),link('series','次へ：級数の除法')]},
 {id:'series',no:'三十六',name:'級数の除法',sub:'係数で割り算',category:'探究 / 級数',title:'多項式の比から、級数の係数を取り出す',intro:'分子と分母を係数で入力し、30次までの商を求めます。掛け戻して確かめることで、級数を式として操作できます。',fields:[field('numerator','分子の係数（定数項→高次）','1','0〜12次。各数24文字・絶対値100万以下',true),field('denominator','分母の係数（定数項→高次）','1, -1, -1','定数項は0以外。ほかの多項式の道具とは入力順が逆です',true),field('order','打ち切る次数 N','12','0〜30の整数')],examples:[['係数が増える級数',{}],['等比級数',{numerator:'1',denominator:'1,-1',order:'10'}],['交代する級数',{numerator:'1',denominator:'1,0,1',order:'10'}]],resultLabel:'指定次数までの商の多項式',badge:'係数を厳密計算',formula:'cₖ = (aₖ − Σⱼ₌₁ᵏ bⱼcₖ₋ⱼ) / b₀',insight:'無限に続く式でも、低い次数からなら必要な係数を順に決められます。',method:'定数項から係数を比較して除算。分母を掛け直し、指定次数まで一致することを確認します。',limits:'入力は定数項が先。分子・分母は12次以下、出力は30次まで。形式的な級数であり、特定のxにおける収束は別に調べる必要があります。',history:'円理では展開した式の係数を扱う計算が重要です。和算の級数研究につながる係数比較を、現代の形式的級数の除法として扱います。',sources:[taylor,ndl],related:[link('arc','建部の円弧級数'),link('segment','次へ：弧と弦に挟まれた面積')]},
 {id:'segment',no:'三十七',name:'弧と弦の求積',sub:'弓形の面積を求める',category:'探究 / 円の求積',title:'円弧に切り取られた面積を求める',intro:'円の半径と弧の高さから、弓形の面積・弦・円弧の長さを計算します。半円より大きい部分にも対応します。',fields:[length('radius','円の半径 R','5'),field('height','弦から円弧までの高さ h','1','0〜直径。小数・分数可')],examples:[['半径5、高さ1',{}],['とても浅い弧',{radius:'1',height:'0.000001'}],['半円より大きい',{radius:'5',height:'8'}]],resultLabel:'弦と円弧に挟まれた面積',badge:approx,formula:'A = R²(θ−sinθ cosθ)　／　θ=2 asin √(h/(2R))',insight:'小さな面積を、大きな面積どうしの差から求めると桁を失います。計算する式の形も大切です。',method:'浅い弧は差の級数を計算し、大きい弧は円から反対側を差し引きます。',limits:'半径0.001〜100万。高さ0〜直径。高さ0は面積0、直径と同じ高さは円全体です。結果は小数近似です。',history:'弧と弦による面積の問いを、円理から続く求積の題材として扱います。現在の逆三角関数による式は、史料の記法そのものではありません。',sources:[ndl,mathworld('円弓形','CircularSegment')],related:[link('arc','円弧級数と比べる'),link('ellipticarc','次へ：楕円の一部分の長さ')]},
 {id:'ellipticarc',no:'三十八',name:'楕円の一部分の長さ',sub:'楕円の弧の長さ',category:'探究 / 曲線の円理',title:'楕円の、選んだ弧の長さを求める',intro:'一周だけでなく、開始位置と終了位置を指定して弧の長さを求めます。分割を増やし、上下からの見積もりが狭まる様子を確かめられます。',fields:[length('a','x方向の半径 a','5'),length('b','y方向の半径 b','3'),field('start','開始の媒介変数角（度）','0','0〜360'),field('end','終了の媒介変数角（度）','60','開始角以上、360以下'),field('parts','分割数','512','16〜4096の整数',true)],examples:[['楕円の一部分',{}],['四分の一周',{start:'0',end:'90'}],['円の場合',{a:'2',b:'2',start:'0',end:'90'}]],resultLabel:'指定した楕円弧の長さ',badge:'分割と上下の見積もり',formula:'L = ∫ √(a²sin²t + b²cos²t) dt',insight:'位置によって進む速さが違う曲線でも、短く区切って足すと長さに近づけます。',method:'各小区間の両端と中点によるSimpson近似と、最小・最大速度による上下界の近似を併記します。',limits:'角度はx=a cos t、y=b sin tのt。中心から見た方角ではありません。上下界の表示も小数近似で、丸め誤差を含む厳密区間ではありません。',history:'後期円理の楕円求積から進む発展用の計算です。任意区間の弧長を、現代の不完全楕円積分と同じ積分として扱います。',sources:[ndl,['NIST DLMF｜楕円積分の定義','https://dlmf.nist.gov/19.2#E5']],related:[link('ellipse','楕円の一周を厳密区間で求める'),link('revolution','次へ：曲線を回して体積へ')]},
 {id:'revolution',no:'三十九',name:'曲線を回す求積',sub:'曲線を回して体積へ',category:'探究 / 立体の円理',title:'曲線を回してできる立体の体積を求める',intro:'多項式とx軸の間を回転させた立体を作ります。断面積の係数を展開し、体積を分数×πの形で厳密に求めます。',fields:[poly('coefficients','半径を表す多項式 P(x)','1, 1, 1'),field('lower','区間の左端','0','24文字・絶対値100万以下'),field('upper','区間の右端','2','左端より大きい数')],examples:[['二次曲線を回す',{}],['円錐に戻る',{coefficients:'1,0',lower:'0',upper:'3'}],['軸を横切る',{coefficients:'1,0',lower:'-1',upper:'1'}]],resultLabel:'回転体の体積',badge:'πの係数を厳密計算',formula:'V = π∫ P(x)² dx',insight:'見た目の複雑な立体でも、断面の規則が分かれば積み重ねて求積できます。',method:'多項式を二乗し、各項の積分を分数で求めます。図は半径の概形です。',limits:'Pは12次以下。x軸まわりの回転。負のPも半径|P|として扱い、重なりを二重に数えません。図は81点の概形です。',history:'『算法求積通考』などの求積に見られる、展開した式を組み合わせる考え方から作った発展用の道具です。ここでは現代の断面積の積分を使用します。',sources:[ndl],related:[link('enritable','円理表と定積分'),link('pappus','次へ：半円の内側の連鎖')]},
 {id:'pappus',no:'四十',name:'半円の内側の連鎖',sub:'接点へ続く円',category:'探究 / 接円の発展',title:'半円の隙間に続く円を、百個先まで求める',intro:'二つの内円と大きな半円の間から、接する円を順に並べます。中心座標と半径を分数で求め、全円の接触条件を検算します。',fields:[length('a','左の内円の半径 a','3'),length('b','右の内円の半径 b','2'),field('number','求める円の個数','10','1〜100の整数',true)],examples:[['十個の円',{}],['左右が同じ',{a:'1',b:'1',number:'6'}],['百個先へ',{a:'2',b:'3',number:'100'}]],resultLabel:'最後の円の半径',badge:exact,formula:'rₙ = ab(a+b)/(a(a+b)+n²b²)　／　yₙ=2nrₙ',insight:'円が小さくなる規則だけでなく、中心の位置まで追うことで連鎖の形を確認できます。',method:'Pappusの円の連鎖を現代の座標で計算。円と円の接触は距離の二乗で厳密照合します。',limits:'n=1が隙間の最初の円。右の内円はn=0。図は最初の20円まで、表は100円まで表示します。',history:'接円・反転の理解を深める比較教材として、Pappusの円の連鎖を取り上げます。この一般公式を和算独自の発見とするものではありません。',sources:[mathworld('Pappusの円の連鎖','PappusChain')],related:[link('inversion','反転の計算へ'),link('cyclic','次へ：四辺と一つの円')]},
 {id:'cyclic',no:'四十一',name:'四辺と外接円の求積',sub:'四辺から面積と円へ',category:'探究 / 容術の発展',title:'四辺から、面積・対角線・外接円を求める',intro:'四つの頂点が同じ円の上にある四角形を計算します。辺の長さから面積の二乗を厳密に求め、対角線と円の半径も表示します。',fields:[length('a','辺 AB','2'),length('b','辺 BC','3'),length('c','辺 CD','4'),length('d','辺 DA','5')],examples:[['四辺が違う',{}],['長方形',{a:'3',b:'4',c:'3',d:'4'}],['正方形',{a:'2',b:'2',c:'2',d:'2'}]],resultLabel:'円に内接する四角形の面積',badge:'平方量を厳密計算',formula:'K²=(s−a)(s−b)(s−c)(s−d)　／　s=(a+b+c+d)/2',insight:'辺の長さだけでは決まらない図形も、円に入るという条件を加えると求積できます。',method:'円に内接する凸四角形の公式を分数で計算し、平方根を小数で表示します。',limits:'辺はAB、BC、CD、DAの順。最大の辺は他の三辺の和未満。一般の四角形や交差する四角形の面積ではありません。',history:'和算の容術から図形の条件を深く考えるための比較教材です。ここでは現代の円に内接する四角形の公式を使い、特定の算額の復刻とはしていません。',sources:[mathworld('円に内接する四角形','CyclicQuadrilateral'),ndl],related:[link('sansha','三斜求積に戻る'),link('tetrahedron','次へ：六辺から立体へ')]},
 {id:'tetrahedron',no:'四十二',name:'六辺から四面体の求積',sub:'六辺から体積へ',category:'探究 / 立体と行列式',title:'六本の辺から、四面体の体積を求める',intro:'面が三角形になっても、立体が作れるとは限りません。六辺の整合性を厳密に調べ、体積の二乗と空間の配置を求めます。',fields:[length('ab','辺 AB','44'),length('ac','辺 AC','117'),length('ad','辺 AD','240'),length('bc','辺 BC','125'),length('bd','辺 BD','244'),length('cd','辺 CD','267')],examples:[['直交する三辺',{}],['正四面体',{ab:'1',ac:'1',ad:'1',bc:'1',bd:'1',cd:'1'}],['平面に退化',{ab:'3',ac:'4',ad:'5',bc:'5',bd:'4',cd:'3'}]],resultLabel:'四面体の体積',badge:'存在条件も厳密判定',formula:'V²=det(G)/36　／　Gᵢⱼ=(ℓᵢ²+ℓⱼ²−ℓᵢⱼ²)/2',insight:'立体の求積と行列式が、一つの問題としてつながります。存在するかどうかも計算の一部です。',method:'Aを基点とする三つのベクトルの内積行列を作り、主小行列式の符号と体積の二乗を有理数で計算します。',limits:'六辺は0.001〜100万。平面に退化する場合は体積0と明示。図は正投影で、面や長さの実寸表示ではありません。',history:'和算の立体求積・消去を先へ進めて考えるための現代的な比較教材です。Gram行列の算法を江戸時代の手法として示すものではありません。',sources:[mathworld('四面体の体積','Tetrahedron'),ndl],related:[link('linear','多元の連立方程式'),link('cylinders','二円柱の相貫体積')]}
];
