/* AI NOBORU — https://www.aiofonesown.com/ | 出典を示す配布用表示。参照史料・第三者の権利表示は各記載を参照。 */
import {q,neg,guard,plus,times,quot,list,product,sum,scale,powerPoly,valueAt,solve,dividePoly,same,integerPolynomial,intervalValue,seriesOutput,trim,textPolynomial,fail,count,pack,fmt,approximateQ,rational,normal} from './frontier-common.mjs';
import {scalar,derivative,coefficients} from './expansion-common.mjs';
import {allRealRoots} from './advanced-algebra.mjs';
export function conic(p){const c=list(p.coefficients,6);if(c.length!==6||c.slice(0,3).every(x=>!x.n))fail('A,B,C,D,E,Fの6係数で二次曲線を入力してください。');const [A,B,C,D,E,F]=c,x=scalar(p.x,'基準点x'),y=scalar(p.y,'基準点y'),t=scalar(p.slope,'傾き');
 const det=A.mul(C).mul(F).mul(q(8)).add(B.mul(D).mul(E).mul(q(2))).sub(A.mul(E.mul(E)).mul(q(2))).sub(C.mul(D.mul(D)).mul(q(2))).sub(F.mul(B.mul(B)).mul(q(2)));if(!det.n)fail('二本の直線などに退化する二次曲線は対象外です。非退化な円・楕円・双曲線・放物線を入力してください。');
 const eval2=(X,Y)=>A.mul(X.mul(X)).add(B.mul(X.mul(Y))).add(C.mul(Y.mul(Y))).add(D.mul(X)).add(E.mul(Y)).add(F);if(eval2(x,y).n)fail('基準点が二次曲線上にありません。');
 const L=[A.mul(x).mul(q(2)).add(B.mul(y)).add(D),B.mul(x).add(C.mul(y).mul(q(2))).add(E)],H=[A,B,C];if(L.every(x=>!x.n))fail('基準点が特異点です。通常の有理媒介式を定められません。');
 const X=sum(scale(H,x),scale(L,q(-1))),Y=sum(scale(H,y),[q(0),...scale(L,q(-1))]);const check=sum(sum(sum(scale(product(X,X),A),scale(product(X,Y),B)),scale(product(Y,Y),C)),sum(sum(scale(product(X,H),D),scale(product(Y,H),E)),scale(product(H,H),F)));if(check.some(x=>x.n))fail('媒介式の代入検算が一致しません。');const den=valueAt(H,t),lin=valueAt(L,t);if(!den.n)fail(lin.n?'この傾きでは第2の有限交点がありません。別の傾きを入力してください。':'この直線全体が曲線に含まれ、第2の交点を一つに定められません。');const point=[quot(valueAt(X,t),den),quot(valueAt(Y,t),den)];if(eval2(...point).n)fail('交点の検算が一致しません。');
 return {...pack(point.map(String).join(', '),lin.n?'指定した傾きに対応する第2の点':'接線の傾き：第2の点は基準点に重なります',['式','分子 / 共通分母'],[['x(t)',textPolynomial(X,'t')],['y(t)',textPolynomial(Y,'t')],['共通分母',textPolynomial(H,'t')]],['基準点を通る直線 y−y₀=t(x−x₀) を代入。','既知の交点に対応する因子を除き、第2の交点を求めます。','媒介式を二次曲線へ戻す恒等式を、全係数で照合済み。'],'有理媒介と交点を厳密検算'),point:point.map(String),verified:true};}
export function curveIntersect(p){const a=scalar(p.a,'二次係数'),b=scalar(p.b,'一次係数'),c=scalar(p.c,'定数項'),h=scalar(p.h,'円の中心x'),k=scalar(p.k,'円の中心y'),r=scalar(p.radius,'半径',.001,1e6);if(!a.n)fail('放物線の二次係数は0以外にしてください。');const f=[c,b,a],v=[c.sub(k),b,a],poly=sum(product(v,v),[h.mul(h).sub(r.mul(r)),h.mul(q(-2)),q(1)]),o=allRealRoots(integerPolynomial(poly),'12');
 const points=o.roots.map(root=>{const l=rational(root.lower),u=rational(root.upper),x=l.add(u).div(q(2)),yr=intervalValue(f,l,u),y=valueAt(f,x);return {x:approximateQ(x),y:approximateQ(y),xRange:[String(l),String(u)],yRange:yr.map(String),multiplicity:root.multiplicity,relative:[approximateQ(x.sub(h).div(r)),approximateQ(y.sub(k).div(r))]};});
 const normalized=[a.mul(r),a.mul(h).mul(q(2)).add(b),valueAt(f,h).sub(k).div(r)];
 return {...pack(points.length+'個の交点','円と放物線の全実交点。小数は近似値。厳密な範囲は分数の区間で確認できます。',['交点','x の目安','y の目安','重複度','x の厳密区間','y の厳密上下界'],points.map((v,i)=>[i+1,fmt(v.x),fmt(v.y),v.multiplicity,v.xRange.join(' ～ '),v.yRange.join(' ～ ')]),['y=ax²+bx+cを円の式へ代入。','得られた多項式：'+textPolynomial(poly),'Sturm列で全実根を分離し、区間演算でyの範囲を求めます。','この置換では各実数xに一つの実数yが対応します。重複度は消去した式での値です。'],'全実根を有理数区間で認証'),points,verified:true,geometry:{type:'frontierIntersections',a:approximateQ(normalized[0]),b:approximateQ(normalized[1]),c:approximateQ(normalized[2]),exactCoefficients:normalized.map(String),points:points.map(v=>v.relative)}};}
export function extrema(p){const f=coefficients(p.coefficients,8),l=scalar(p.lower,'区間の左端'),u=scalar(p.upper,'区間の右端');if(u.sub(l).n<=0n)fail('左端より大きい右端を入力してください。');const d=derivative(f),candidates=[{x:[l,l],v:[valueAt(f,l),valueAt(f,l)],kind:'左端'},{x:[u,u],v:[valueAt(f,u),valueAt(f,u)],kind:'右端'}];if(d.length>1){for(const r of allRealRoots(integerPolynomial(d),'12').roots){let a=rational(r.lower),b=rational(r.upper);if(b.sub(l).n<0n||a.sub(u).n>0n)continue;if(a.sub(l).n<0n)a=l;if(b.sub(u).n>0n)b=u;candidates.push({x:[a,b],v:intervalValue(f,a,b),kind:'停留点の候補'});}}
 const cmp=(a,b)=>a.sub(b).n<0n?-1:a.sub(b).n>0n?1:0,lo=candidates.map(c=>c.v[0]).sort(cmp),hi=candidates.map(c=>c.v[1]).sort(cmp),minimum=[lo[0],hi[0]],maximum=[lo.at(-1),hi.at(-1)];return {...pack('最小 '+minimum.map(x=>fmt(approximateQ(x))).join(' ～ ')+' ／ 最大 '+maximum.map(x=>fmt(approximateQ(x))).join(' ～ '),'閉区間全体の最小値・最大値。小数は目安、厳密区間は途中式に表示。',['候補','x の区間','値の厳密な上下界'],candidates.map(c=>[c.kind,c.x.map(String).join(' ～ '),c.v.map(String).join(' ～ ')]),['導関数：'+textPolynomial(d),'端点と導関数の全実根を調べます。','最小値の厳密区間：'+minimum.map(String).join(' ～ '),'最大値の厳密区間：'+maximum.map(String).join(' ～ '),'小数の表示が同じでも、厳密値かどうかは分数の上下界で確認できます。'],'端点・停留点と区間演算'),minimum:minimum.map(approximateQ),maximum:maximum.map(approximateQ),exactMinimum:minimum.map(String),exactMaximum:maximum.map(String)};}
const choose=(n,k)=>{let v=1n;for(let i=1;i<=k;i++)v=v*BigInt(n-i+1)/BigInt(i);return q(v);};
export function bernstein(p){const f=coefficients(p.coefficients,12),l=scalar(p.lower,'左端'),u=scalar(p.upper,'右端'),depth=count(p.depth,'分割の深さ',0,7);if(u.sub(l).n<=0n)fail('左端より大きい右端を入力してください。');const n=f.length-1,affine=[l,u.sub(l)];let a=[q(0)];f.forEach((v,i)=>a=sum(a,scale(powerPoly(affine,i),v)));const B=Array.from({length:n+1},(_,k)=>{let v=q(0);for(let j=0;j<=k;j++)v=plus(v,times(a[j]||q(0),quot(choose(k,j),choose(n,j))));return v;});let leaves=[{l,u,b:B}];for(let h=0;h<depth;h++){const next=[];for(const s of leaves){let row=s.b,left=[row[0]],right=[row.at(-1)];while(row.length>1){row=row.slice(1).map((v,i)=>quot(plus(row[i],v),q(2)));left.push(row[0]);right.unshift(row.at(-1));}const mid=quot(plus(s.l,s.u),q(2));next.push({l:s.l,u:mid,b:left},{l:mid,u:s.u,b:right});}leaves=next;}
 const cmp=(a,b)=>a.sub(b).n<0n?-1:a.sub(b).n>0n?1:0,values=leaves.flatMap(s=>s.b).sort(cmp),bounds=[values[0],values.at(-1)];return {...pack(bounds.map(String).join(' ≤ f(x) ≤ '),'左が下界、右が上界。区間全体を含む厳密な範囲。',['区間','下界','上界'],leaves.map(s=>{const a=[...s.b].sort(cmp);return [s.l+' ～ '+s.u,String(a[0]),String(a.at(-1))];}),['区間を0〜1に移し、Bernstein基底の係数へ変換。','非負で総和1の基底なので、関数の値は係数の最小値と最大値の間に入ります。','二等分を繰り返し、各区間の係数をde Casteljau法で厳密に更新。','この上下界は安全な包み込みです。分割が有限なので、真の最小値・最大値と一致するとは限りません。'],'区間全体を分数で包み込む'),bounds:bounds.map(approximateQ),exactBounds:bounds.map(String)};}
export function partialFractions(p){const a=coefficients(p.numerator,12);const s=normal(p.factors);if(!s||s.length>600)fail('因子の入力は600文字以内にしてください。');const rows=s.split('\n');if(rows.length>10)fail('因子は10行以内です。');const factors=rows.map(row=>{const pair=row.trim().split(/[,、\s]+/);if(pair.length!==2)fail('各行に根rと重複度mを入力してください。');return {r:scalar(pair[0],'根'),m:count(pair[1],'重複度',1,10)};});if(factors.reduce((a,b)=>a+b.m,0)>10)fail('分母の合計次数は10以下にしてください。');if(factors.some((a,i)=>factors.slice(0,i).some(b=>!a.r.sub(b.r).n)))fail('同じ根は一行にまとめてください。');const D=factors.reduce((a,{r,m})=>product(a,powerPoly([neg(r),q(1)],m)),[q(1)]),{quotient,remainder}=dividePoly(a,D),basis=[],terms=[];for(const {r,m} of factors)for(let k=1;k<=m;k++){basis.push(dividePoly(D,powerPoly([neg(r),q(1)],k)).quotient);terms.push({root:String(r),power:k});}const solution=solve(Array.from({length:D.length-1},(_,i)=>basis.map(b=>b[i]||q(0))),Array.from({length:D.length-1},(_,i)=>remainder[i]||q(0)));let check=product(quotient,D);basis.forEach((b,i)=>check=sum(check,scale(b,solution[i])));if(!same(check,a))fail('部分分数の復元が一致しません。');terms.forEach((t,i)=>t.coefficient=String(solution[i]));return {...pack([...(quotient.some(x=>x.n)?[textPolynomial(quotient)]:[]),...terms.filter((t,i)=>solution[i].n).map(t=>`(${t.coefficient})/(x−(${t.root}))^${t.power}`)].join(' ＋ ')||'0','多項式部分と、各極に対応する部分分数',['根 r','分母 (x−r) の指数','分子の係数'],terms.map(t=>[t.root,t.power,t.coefficient]),['分母：'+textPolynomial(D),'まず多項式の割り算で商と真分数に分離。','共通分母を掛けた係数方程式を解き、元の分子の全係数を再現。','元の分母が0になる点では、式は定義されません。'],'分数を合成し直して厳密照合'),terms,verified:true,quotient:quotient.map(String)};}
