/* AI NOBORu — https://www.aiofonesown.com/ | 出典を示す配布用表示。参照史料・第三者の権利表示は各記載を参照。 */
const input=(key,label,value,hint='',wide=false)=>({key,label,value,kind:'text',hint,wide});
const select=(key,label,value,options)=>({key,label,value,kind:'select',options});
const link=(id,name)=>({id,name});
const seki=['国立国会図書館｜括要算法と累乗和','https://www.ndl.go.jp/math/s2/2.html'];
const enri=['小川束｜近世日本の円理','https://www.jstage.jst.go.jp/article/emath1996/1999/Spring-Meeting/1999_Spring-Meeting_38/_article/-char/ja/'];
const elliptic=['NIST DLMF｜楕円積分の級数','https://dlmf.nist.gov/19.5'];
const replacement=['後藤・小松｜和算の換式と終結式','https://www.kurims.kyoto-u.ac.jp/~kyodo/kokyuroku/contents/pdf/1392-11.pdf'];
const mobius=['IMA｜メビウス変換による円の連鎖','https://ima.org.uk/wp/wp-content/uploads/2017/12/Exploring-Steiner-Chains-with-Mobius-Transformations-from-MT-Dec-17.pdf'];
const radius='0.001〜1,000,000。整数・小数・分数';
export const masteryCatalog=[
 {id:'bernoulli',no:'二十二',name:'ベルヌーイ係数と累乗和',sub:'和を作る、多項式そのものへ',category:'極みⅠ / 代数',title:'大きな和の奥にある、係数の規則を取り出す',intro:'40乗までの累乗和を厳密に求め、どんな N にも使える多項式を作ります。係数の表と差分の恒等式から、式そのものが正しいことも確かめます。',fields:[input('n','最後の数 N','10','0以上、80桁以内の整数'),input('power','累乗 p','10','0〜40の整数')],examples:[['10乗の和',{n:'10',power:'10'}],['40乗の和',{n:'10',power:'40'}],['1兆項の平方和',{n:'1000000000000',power:'2'}]],resultLabel:'1ᵖ + 2ᵖ + … + Nᵖ',badge:'多項式まで厳密',formula:'Sₚ(N) = Σ C(p+1,j) βⱼ N^(p+1−j) / (p+1)',insight:'数を足し続ける代わりに、和を生み出す係数の規則を求めます。',method:'β₁=+1/2 の約束。係数生成は現代の有理数漸化式で再構成し、S(N)−S(N−1)=Nᵖ を全係数で検算します。',limits:'N は80桁まで、p は0〜40。N=0 は空の和。すべて整数・分数で計算します。',history:'関孝和『括要算法』巻之亨では、有限個の和の問題からベルヌーイ数にあたる係数が導かれます。この道具の記号と係数生成手順は現代的な再構成です。',sources:[seki],related:[link('tawara','俵杉算と累乗和'),link('enritable','次へ：円理表と定積分')]},
 {id:'enritable',no:'二十三',name:'円理表と定積分',sub:'積分の値を、規則の表に',category:'極みⅡ / 円理',title:'曲線の下の広さを、分数の表で求める',intro:'六龍三陽表につながる xᵖ(1−x)ᑫ の積分を計算します。三角関数の型へ切り替えると、楕円や立体の求積に必要な係数も取り出せます。',fields:[select('mode','積分の型','1',[1,2]),input('p','指数 p','2','0〜40の整数'),input('q','指数 q','3','0〜40。型1：xᵖ(1−x)ᑫ、型2：sinᵖθ cosᑫθ')],examples:[['六龍三陽表の型',{mode:'1',p:'2',q:'3'}],['πを含む積分',{mode:'2',p:'2',q:'2'}],['大きな指数',{mode:'1',p:'40',q:'40'}]],resultLabel:'指定した定積分の厳密値',badge:'分数・πを厳密表示',formula:'I(p,q) = p!q!/(p+q+1)!　／　J(p,q) = (p−1)J(p−2,q)/(p+q)',insight:'毎回別の問題として解かず、指数を動かす規則と表にまとめます。',method:'型1は0〜1、型2は0〜π/2で積分。漸化式を分数で計算し、型2は必要に応じてπを文字のまま残します。',limits:'p,q は0〜40。表は0〜6の範囲を抜粋し、指定指数の答えを別に表示します。図は小数で描く概形です。',history:'江戸後期の円理では、展開した式を項ごとに積分し、級数の和を表にする方法が発展しました。六龍三陽表の積分の型を現代記号で扱い、三角関数の型を補助として添えています。',sources:[enri],related:[link('bernoulli','ベルヌーイ係数と累乗和'),link('ellipse','次へ：楕円の周長')]},
 {id:'ellipse',no:'二十四',name:'楕円の周長',sub:'円を越えた、曲線の長さ',category:'極みⅢ / 円理',title:'楕円の長さを、確かな上下界で囲む',intro:'長い半径と短い半径から、楕円の一周の長さを求めます。項数を増やし、残りの項と丸め誤差を含む区間がどう狭くなるか比べられます。',fields:[input('a','半長軸 a','5',radius),input('b','半短軸 b','3','a,b の大小は自動で整理'),input('terms','級数の項数 N','100','1〜1000。細長い楕円では多くの項が必要')],examples:[['5と3の楕円',{a:'5',b:'3',terms:'100'}],['細長い楕円',{a:'10',b:'1',terms:'300'}],['円に戻る',{a:'3',b:'3',terms:'1'}]],resultLabel:'楕円の周長 L',badge:'剰余込みの厳密区間',formula:'L = 4a E(m) = 2πa(1−Σ tₙ)　 m=1−b²/a²',insight:'無限に続く計算でも、残った部分を押さえれば答えを区間で保証できます。',method:'現代の楕円積分と同値な正項級数を使用。πの保証区間、各段の外向き丸め、残差上限を合わせます。ここで E は母数 m の記法です。',limits:'入力は半軸の長さです。表示24桁すべてが確定桁ではありません。細長い場合は、表示された区間幅で精度を判断してください。',history:'小出兼政『円理算経』（1842年）の楕円周長計算は、和田寧から伝わる後期円理として研究されています。ここでは問題に学び、現代の級数と保証付きの計算で再構成します。',sources:[['黄俊瑋｜和算の楕円周長計算の研究','https://www.airitilibrary.com/Article/Detail/a0000578-202112-202112290013-202112290013-42-51'],elliptic],related:[link('enritable','円理表と定積分'),link('cylinders','次へ：二円柱の相貫体積')]},
 {id:'cylinders',no:'二十五',name:'二円柱の相貫体積',sub:'交差する立体を、積分する',category:'極みⅣ / 立体の円理',title:'二本の円柱が重なる体積を求める',intro:'軸が直角に交わる二本の円柱。その両方に含まれる立体の体積を求めます。半径が違う場合も、断面と級数から上下界を計算します。',fields:[input('a','円柱Aの半径','2',radius),input('b','円柱Bの半径','1',radius),input('terms','級数の項数 N','100','1〜1000')],examples:[['半径2と1',{a:'2',b:'1',terms:'100'}],['半径が近い場合',{a:'1',b:'.99',terms:'300'}],['同じ半径',{a:'3',b:'3',terms:'1'}]],resultLabel:'共通部分の体積 V',badge:'断面から保証区間へ',formula:'V = 8∫₀ᵇ √(b²−z²)√(a²−z²) dz　（a≥b）',insight:'一つの断面を求め、連続して積み重ねることで、見通しにくい立体へ進みます。',method:'円柱の軸は直角に交差。断面積を積分する現代の級数で再構成し、正の残差と丸め誤差を外向きに押さえます。',limits:'円柱は共通部分を切り取らない十分な長さとします。半径が等しい場合は16r³/3を厳密計算。それ以外は区間幅で精度を確認します。図は断面積の変化です。',history:'安島直円は、直角に交わる円柱の相貫体積を扱った和算家として数学史に記録されています。ここでは半径の異なる場合まで、現代の記号と保証区間を備えて計算します。',sources:[['Smith・Mikami｜A History of Japanese Mathematics','https://archive.org/details/historyofjapanes00smit'],['Hubbell｜交差する円柱の体積（NBS）','https://doi.org/10.6028/jres.069C.017'],enri],related:[link('ellipse','楕円の周長'),link('replacement','極意へ：換式による消去')]},
 {id:'replacement',no:'二十六',name:'換式による一般消去',sub:'関の換式を、文字係数で',category:'極意Ⅰ / 代数',title:'高い次数を落とす、換式の仕組みを使う',intro:'y の1〜4次の二つの式から y を消します。係数には x の多項式を置けます。換式の小さな行列と、現代の大きな行列を厳密に照合します。',fields:[{...input('f','前式 f(x,y) の係数','1\n0\n0\n-1, 0','y の最高次から定数まで1行ずつ。各行は x の最高次から係数を並べる。例は y³−x',true),kind:'textarea'},{...input('g','後式 g(x,y) の係数','1\n0\n-1','各行 x の2次以下。整数係数−1000〜1000。例は y²−1',true),kind:'textarea'}],examples:[['三次と二次',{f:'1\n0\n0\n-1, 0',g:'1\n0\n-1'}],['最高次係数が消える',{f:'1, 0\n1',g:'1, 0\n2'}],['共通因子がある',{f:'1\n0\n-1, 0, 0',g:'1\n-1, 0'}]],resultLabel:'y を消した必要条件',badge:'二つの行列式を厳密照合',formula:'h₁ = bₘf − aₙy^(n−m)g　／　det H = (−1)^(nm) Resᵧ(f,g)',insight:'高い次数の項を打ち消し、未知数を消せる小さな表へ変換します。',method:'研究文献の換式を現代の多項式表記で構成。全計算は整数多項式。同じ入力からシルベスター行列式も独立に展開し、符号を含め照合します。',limits:'y の次数1〜4、各係数は x の2次以下。消去式は最大16次。実根への引き渡しは8次以下かつ係数絶対値10¹⁸以下。元の式への代入確認が必要です。',history:'関孝和の消去研究に現れる「換式」を扱います。符号・等号・多項式の表示は後藤・小松の研究に沿う現代的転写で、初期写本の誤りまで再現するものではありません。',sources:[replacement,['森本光生｜和算の連立代数方程式','https://www.kurims.kyoto-u.ac.jp/~kyodo/kokyuroku/contents/pdf/1787-04.pdf']],related:[link('elimination','二次式の消去に戻る'),link('roots','高次方程式の実根'),link('inversion','次へ：反転で円と直線をつなぐ')]},
 {id:'inversion',no:'二十七',name:'反転で円と直線をつなぐ',sub:'複雑な配置を、解ける形へ',category:'極意Ⅱ / 幾何の変換',title:'円を反転し、中心と半径を正確に求める',intro:'原点を中心に図形を反転します。円が別の円へ移る場合も、直線になる場合も、分数で判定。円の中心と、中心点の像の違いまで確かめられます。',fields:[input('x','元の円の中心 x','3','絶対値1,000,000以下。小数・分数可'),input('y','元の円の中心 y','0'),input('r','元の円の半径 r','1',radius),input('k','反転円の半径 k','2',radius)],examples:[['円から円へ',{x:'3',y:'0',r:'1',k:'2'}],['円が直線になる',{x:'1',y:'0',r:'1',k:'2'}],['原点を囲む円',{x:'0',y:'0',r:'3',k:'2'}]],resultLabel:'反転後の図形',badge:'ゼロの判定も厳密',formula:'Δ = x²+y²−r²　／　中心 = k²(x,y)/Δ、半径 = |k²r/Δ|',insight:'接する配置を保つ変換で、難しい図形を扱いやすい形へ移します。',method:'反転の中心は原点。Δ=0なら直線として別に計算します。2回の反転で元の中心と半径に戻ることを分数で検算。図は左右で尺度を調整します。',limits:'入力は24文字以内。原点そのものの像は定義されません。原点での接触は有限の接触として残らない場合があります。',history:'六球連鎖や環円の構造を理解するための、現代的な補助道具です。この一般的な反転公式や証明を、そのまま江戸時代の和算家の手法として帰属させてはいません。',sources:[mobius,['深川・堀部｜算額と六球連鎖','https://archive.bridgesmathart.org/2014/bridges2014-111.pdf']],related:[link('hexlet','六球連鎖の仕組みに戻る'),link('steiner','次へ：非同心の円の連鎖')]},
 {id:'steiner',no:'二十八',name:'非同心の円の連鎖',sub:'輪が閉じる、その条件へ',category:'極意Ⅲ / 環円',title:'大きさの違う円の輪は、いつ閉じるか',intro:'中心がずれた内外二円の間に、互いに接する円をつなぎます。閉じる条件を調べ、開始位置を変えても輪が閉じる不思議を、中心と半径まで計算します。',fields:[input('outer','外円の半径 R','3',radius),input('inner','内円の半径 r','2/3'),input('offset','中心のずれ d','5/3','0以上、d+r<R'),input('number','つなぐ円の個数 n','6','3〜24。一周で閉じる輪を判定'),input('phase','開始角（度）','0','0〜360。変換先の同心円上での角度')],examples:[['大きさの違う6円',{outer:'3',inner:'2/3',offset:'5/3',number:'6',phase:'0'}],['開始位置を変える',{outer:'3',inner:'2/3',offset:'5/3',number:'6',phase:'30'}],['閉じない5円',{outer:'3',inner:'1',offset:'0',number:'5',phase:'0'}],['4円の輪',{outer:'3',inner:'1/2',offset:'1/2',number:'4',phase:'0'}]],resultLabel:'円の連鎖の閉鎖判定',badge:'接触・戻り位置・重なり',formula:'C = (R²+r²−d²)/(2Rr)　／　δ = 2 asin √((C−1)/(C+1))　／　nδ = 2π',insight:'出発する円の大きさが変わっても、二つの境界円の関係が同じなら閉鎖条件は変わりません。',method:'メビウス変換で同心円へ移し、円を並べて戻します。戻り位置は独立に生成。3・4・6円の閉鎖条件は有理数で厳密判定し、実際の配置は小数で検算します。',limits:'r≥R/1,000,000、間隔R−d−r≥R/10,000,000。ほかの個数は数値判定。何周もして戻る配置や、途中で重なる配置は一周の輪と区別します。',history:'安島直円の環円研究につながる現代的な再構成です。ここで使う一般の閉鎖定理や変換による証明を、安島の原稿そのものとして示すものではありません。',sources:[['小曽根淳｜和算の環円図形と文様','https://repository.kulib.kyoto-u.ac.jp/dspace/handle/2433/243743'],mobius],related:[link('inversion','反転の計算へ戻る'),link('hexlet','空間の六球連鎖と比べる')]}
];
